// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MyInput: typeof import('./src/components/myInput/MyInput.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
  }
}
