// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using interviewer.Data;

#nullable disable

namespace interviewer.Migrations
{
    [DbContext(typeof(InterviewerDbContext))]
    [Migration("20230901051014_AddSingInManager")]
    partial class AddSingInManager
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bf3b5dd6-263b-44c5-95d5-0392d4855eea"),
                            ConcurrencyStamp = "ffdde4fd-6055-46af-899e-9fe68601342a",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("48622ea5-0d59-4e9e-b9e6-47db128533bf"),
                            ConcurrencyStamp = "16a87b09-7a52-47fd-a1ae-5551f13acdc0",
                            Name = "Interviewer",
                            NormalizedName = "INTERVIEWER"
                        },
                        new
                        {
                            Id = new Guid("acd3e7f3-f42b-4ce4-812d-f86f8afc2ebd"),
                            ConcurrencyStamp = "c593ae35-84e9-4271-8df2-d296b423724b",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("interviewer.Data.Comment", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepId")
                        .HasColumnType("int");

                    b.Property<string>("InterviewerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("interviewer.Data.Interviewer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interviewers");
                });

            modelBuilder.Entity("interviewer.Data.InterviewerUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("interviewer.Data.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("College")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FirstDepartment")
                        .HasColumnType("int");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SecondDepartment")
                        .HasColumnType("int");

                    b.Property<string>("Skills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeChat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f49e2403-dfca-44ed-a7f2-c64c4126068f"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("5234d693-bb18-4236-ac77-3c1a80ec94fc"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("ea7cb714-c023-41c4-ac56-6bd0b7ba5768"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("90b31671-648c-436f-97e1-fb57bd5b80ac"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("e367fd46-a737-4b61-b4e9-de169c95e783"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("264d0ebd-821e-4569-b8d1-67f519f17566"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("4b7a1611-96cd-440e-94d1-379c28af5713"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("35e2ad47-cdd7-4523-b6c0-c9942b27b052"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("f250bd8a-6d4b-4a63-ae7c-fbfb93c01cc9"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("925df3ae-499a-42e5-9e97-601adf8f4327"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("f8ecb7f6-359d-43dc-afc1-0787ce00d873"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("61dacfce-f54e-4249-97c7-8c849db20f43"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("b3db3685-25e3-488d-86dd-f53a78766cc9"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("fd7536e6-f6b5-4b30-a0ed-dffdfaf615ee"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("6bef99ae-9cbf-4da1-932d-61f5a5494bbc"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("c10f48f1-c37f-4d74-b3e1-8c0caa23ea9f"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("7a4ce336-a3dd-48d0-a86c-18e39ab82f87"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("9acb730a-9512-4797-8ee5-2247946bd8bd"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("0e7b7915-c34d-47a8-b756-136c49a87456"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("8cf0084b-0e1d-4a27-ab7a-8b9653a12539"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("e1e5e404-3a76-41e2-ae96-42834526a59e"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("ba562f18-0e19-4f3c-a588-90eee47579fe"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("8a86aaac-66db-4de7-8821-f284a9a5d40e"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("47126ab3-a520-46cd-ab89-704280f353f0"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("32455910-2279-4571-a84a-fc5cacdb1ad8"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("5d6edd33-be63-4efe-8aa5-ae1357535bf5"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("a9b385df-949a-42df-a3da-b2fd8e48315b"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("357217a3-9e72-4fbc-9250-3b86038accb9"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("472985fa-5daf-4c0b-bb17-f0ece22a4e4d"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("173aeadd-2f7c-4dfc-bbf9-b3c52d8edafe"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("b90c25f1-93a5-4a72-ad0f-310be0a6966f"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("ef1f7bf5-bf35-4112-a116-e695e56a5454"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("9c7b1437-dd03-4c77-b7b1-6523a854879b"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("c4054f7a-841f-4615-8116-49f610d27182"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("e9a49d45-b755-48a9-aafa-88746de1317c"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("f93ab696-0429-4a29-acba-9b5f2de2fd6e"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("69f5a84c-2a91-4996-96d6-ef5e4c474df9"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("d0b165d9-9edc-4377-87b3-6078e7e4f54a"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("f4f074d4-2f04-4e73-829d-17d6b77cacbd"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("baa5d3e1-05a7-4bfa-bd23-b82d4eee1706"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("cf447d2d-c56f-4bce-be6b-30d963ab6568"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("68a5fde2-206c-4ce5-b5b1-3cd87e2afb3b"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("462783ac-197e-477c-9bd4-8b75c52b5c91"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("4be1161c-35e5-440f-b03a-bfac94799946"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("ae07e84f-0d32-4c7d-a830-d4252cb18522"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("b656e414-6af8-45f5-9c2e-ddef924ebaad"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("f20a8df1-18ea-459f-80e4-dce2a8f0fd56"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("267a9851-e49f-4947-b8c5-f67809800e71"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("c3ab51e5-4c97-4242-8382-af6670d0f2ad"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("b7e0eeef-b956-4197-8c4f-72d0df0f48b6"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("6fd4c29d-a71f-4f18-a14a-a3e2823bc764"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("db3dcbab-7c3c-4b2a-bd05-9a5f1318699b"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("53b8d57e-eff6-4b50-9420-6f04ec63ee62"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("70e2a3bf-0c2c-4a5a-a737-3a774ffbc0ae"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("2f71e53a-b749-4960-92f8-ff317c982b05"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("9057f65d-26a3-4134-8b16-cf488b4c467b"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("e891b704-4c76-4b00-991b-ba848493e016"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("29b03e2f-be45-480d-bfc9-b96e88957d66"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("343be415-3044-4302-a52d-d98b4f089181"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("ebfbffda-b66a-453d-9a73-8068527be841"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("7b61225b-90d2-40a7-b85f-a8cdddbfb2de"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("eef8891d-b789-4a28-9cca-202077d6766b"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("56a546ef-8444-4d0d-afba-1fa71fbf22d5"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("327ac977-5432-45f5-8b9f-cdbe5756e80c"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("adf4d890-66b1-461c-bcf7-ec3df14a2a0f"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("21bd5db3-0e23-43e8-9097-fc26789f6d78"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("ee6c045c-0c7c-427b-9828-4b20aab99678"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("c018a7fd-3320-41c6-90b8-42955667665c"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("5b22577c-c725-45bd-9d5a-af7929fb0066"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("e1319eb9-9645-46db-b934-ab5602a86cc2"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("8fa56ad6-3587-40e2-a92d-a0c2e5f25146"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("75f38c44-f5b6-4e5c-9f48-6836e96d50d9"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("298014f7-c166-417c-81f7-41152cb0051a"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("e641e9a4-6786-4a1c-86d3-3b45caa923f8"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("c17f0ec5-e28e-424c-96bf-9e3ed03d15f2"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("51489cf5-48d3-4a23-8ad7-ae74b33d2e10"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("764484f8-7906-42da-afbc-c75137442aa6"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("51be9d74-f8dc-4b98-b41c-5fcca5345569"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("9ac42ef5-db80-4541-ac73-a6d092b4f3a6"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("5215e686-fc0e-47d6-8e7c-e5e0dbab9794"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("1847dd74-8979-4ef5-946e-345a95564636"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("ce7a1e3b-8d43-4806-b9b9-c7804e67d373"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("57862187-77f9-4614-bb1e-c193a3638ce0"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("bcff8031-bf0b-4a8c-8653-31127f2ff648"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("8c5f5a6e-8517-4237-979a-8b069479f18a"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("8a77c3da-ff73-4c61-bfd1-f6ef77dc53ef"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("9288b6bf-6e8e-45da-8e38-1427b4e038f4"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("7978f100-8757-42e8-b4d3-c62e0b684fad"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("5b7c4757-ae7b-45cd-b363-9a43043ad89f"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("21c9d77d-89f1-4924-869b-d4f8523bf95a"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("4c386985-cef4-4345-9321-d07697f3543e"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("e04e762b-3110-46b7-85a0-4c0b9014a6f0"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("5a143dc9-c115-44c5-87ee-903b7b40e314"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("6f560cdf-9a8d-46c9-af09-90bab3dd5c49"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("1b9d779a-0539-4f4e-bf56-5e56c66afa3f"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("761f871a-f960-4f61-9102-1f996d3bd545"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("e6fa3fee-3649-4829-82ac-c7aa3ab94fc5"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("60eb1ab1-c4b4-4385-9cff-9371affc8c09"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("1055e179-d80c-469a-b172-1341fa1969b7"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("a805ec5d-37fa-4ae9-8a9c-4b7771fcf25c"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("interviewer.Data.InterviewerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("interviewer.Data.InterviewerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("interviewer.Data.InterviewerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("interviewer.Data.InterviewerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
