// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using interviewer.Data;

#nullable disable

namespace interviewer.Migrations
{
    [DbContext(typeof(InterviewerContext))]
    [Migration("20230827145239_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("interviewer.Data.Interviewer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interviewers");
                });

            modelBuilder.Entity("interviewer.Data.InterviewerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InterviewerAccounts");
                });

            modelBuilder.Entity("interviewer.Data.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("College")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FirstDepartment")
                        .HasColumnType("int");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SecondDepartment")
                        .HasColumnType("int");

                    b.Property<string>("Skills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeChat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7fbdb46b-01fe-4bff-9da2-0f8e15e6f8bc"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("97d8ba7f-8d3e-47f5-b34b-5a02b37d742e"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("2568f7bf-94bb-4f81-851e-1413d455a5d7"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("8c7cf603-cbcb-4240-ac0d-de7ce219f2ed"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("f4b70234-f51b-4f21-ae94-7e9ed0d63113"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("0ec9293d-575a-450c-840d-b29d7ac3f694"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("cbe90a70-2442-4668-8232-b2247351ef96"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("4e4e0378-9619-43aa-ab23-50d9b40d8eab"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("ad3e6aa6-16b8-4b14-908a-e46dbcbc3d9a"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("a556b090-d5f1-4a83-bb99-7eac1fc9dd32"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("66008bd0-fe47-452b-b632-ab50387e23a4"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("53777e55-fae2-4b1f-b46c-30276efbba23"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("f9b9a86f-2900-4bfe-abb4-6bfbd0e871e9"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("2c1ef94a-78d7-4a10-a6b7-6f1f32f5a398"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("9da8c426-241d-4a29-ba52-dc2340c70ce3"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("62e14b3a-a3e3-4698-a702-5534ca7243c0"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("1dc4e750-e03e-4d16-9833-b73f6b975306"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("2bd63cca-a422-485b-959a-db34799566a9"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("a91696a2-9a84-40d1-987f-16f140a1889e"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("14384888-db80-4899-8b72-af9e06ce83f0"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("359f8690-add4-4302-a34e-c1712eb53879"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("6d73b99e-93e2-42c1-a735-d8159202ed10"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("1bddfc66-5941-4bb6-873c-95fd87f02405"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("f9deeb6f-8ca9-42f6-a12d-13f90440fccd"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("71ec3886-9011-4dc2-bf74-ac521e890ba9"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("3bdec72c-27a7-4b98-a529-7c6527edae0a"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("2d4cc2cd-e289-4639-be94-abfc46e29996"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("cfa4a663-00a0-4ffb-b7ad-bfec71bc6810"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("f05e4ce6-815a-4799-b07f-fa2ebb24fde6"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("4e9eb1f5-5fb1-4bd5-a313-a2f94f5eb987"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("12303e73-cb77-43c2-8e53-db2eec1249dc"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("7fe77ab7-791f-4ecf-a24c-321c905da5ac"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("5ce1e7b3-c6af-476a-bf98-9a7560362de3"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("2a7f2672-99da-4380-a8bd-caf850750b2f"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("861cc60a-fbb2-46bf-b125-471959592200"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("33fb28dd-a7ee-47aa-837e-d8462963bab4"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("e49a15a3-6acf-4af1-95f0-90a498d1f573"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("25b9ae4e-3503-4b37-bc22-f84935d74d06"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("e48106ad-726c-4f93-8ac5-67f5d0ed1948"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("77864514-3fc8-42a5-9342-b18184b68ae4"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("0c3505cf-0dca-40e9-b2b4-bc6c433fa329"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("3276c67b-8044-43cc-b84d-7778b6a1e313"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("1e60a1a4-1873-44c7-bdd8-90d06e117ba5"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("d4bedf30-abeb-4f77-9714-318311a9131f"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("8eec7d7f-119d-4686-8f6b-ec16d177c031"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("2880a2ec-6429-4801-8642-629cb8da1cf8"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("3bc6b261-6787-487a-9fb2-6665f06fddfb"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("fbb6a63f-b67b-44c2-b525-5bb6a99bb52d"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("d8289cf1-2e04-4849-a3e5-fefce106f395"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("aa5dd587-9074-4b97-b45e-dfacda3d75e2"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("f73d7917-9b64-4404-8dc3-667f51cc7bf7"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("c12824dc-b2f8-4019-815a-846e1abe89e8"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("bc79aa35-e772-4c09-8770-37bd907ecd0e"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("617d8d7b-9e90-45c2-b8bd-d1aeea38d556"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("a559ab85-402f-4d78-accf-ddf2cc802408"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("0633a86b-63ef-400d-8e4d-e50abcae2b54"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("ec13bb8b-bd56-4da3-b26d-b4efc1588ad8"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("9f73cb55-e527-46ae-b135-1e39a0ee6741"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("d829f374-6846-44e7-af6d-bf81d4cc08b8"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("e798b0c8-ea59-42c5-9059-a8fadd11519c"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("e995b071-5bc9-4d66-b526-b0fc9e06a3c2"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("37b4400e-e607-4cc5-afca-7e7f80263028"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("1a65fdc5-4ae8-46c0-8baf-2916ea036e2b"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("5357a12e-4f4a-4f38-bcba-0af86643151c"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("2260a7cb-209a-46e2-8ba9-a6bc32bd5561"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("8d4a76ba-ef2e-4b02-af69-616284c557e8"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("c5282ed3-c808-41a8-b273-5ad37e5ec35a"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("fc98dcdb-bb0b-424a-a314-a737846bc6f2"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("8bb69bd3-3260-4f0a-8309-e71aae8c4ed1"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("a2b56364-f458-44f0-9595-56ccdb34e31b"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("730b3397-a812-44ed-90e8-3da73b382842"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("e27eb08f-31bd-4890-aaf3-4127c6936b82"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("bcf36a21-3f79-4f2b-a479-c2cb64fec74b"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("cb170f60-7023-4106-a215-7dd5a33043bc"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("4c144ae2-07a7-4bcb-a1f8-45503761fa0b"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("9e1ec3cd-8c25-4c46-b804-bed1aecae669"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("b09ce400-a979-4dc5-a979-8bf52f976606"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("af399c73-4464-4ea1-bb96-125b33d25702"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("badeed9c-1f55-4ad5-bd86-7758d5f436e2"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("0691ac51-6378-47f0-a7d5-795437eb6ce8"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("7bf16ab2-8e1b-4080-b6e1-34b81216de06"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("17434036-991f-4433-874d-ec1d9808e2e3"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("71f28f02-78ec-49de-a838-672de3137869"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("3dbde933-7676-4201-889d-32718b5efe50"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("baff6090-e12c-4647-bec3-082d3f5a2c5a"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("315cd767-78c9-48e0-b6c1-7c292c92f491"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("288bb338-f320-4d88-bda8-99e768cc18dd"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("63967f83-010e-46ff-b940-f2be93e92cbd"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("82804c54-4e83-41ec-ae4a-4b617d946c38"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("df0d0b3b-e821-418a-be03-988ba1042a0e"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("3dbf13dc-bccb-458c-a492-e156932322f6"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("ab5a0f20-a703-4761-ba81-d19140d23e61"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("dfe954be-f4df-49c7-bd91-3745f5e5439e"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("f3edf26b-24c4-4292-8dcc-4279080623c2"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("312db54c-1a30-4fbc-ad62-0ef3e8f88a6d"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("67a25d74-a2fc-471b-b9ab-4ac5ac8aca9a"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("553abdd9-e0c0-4783-8425-5b2904b55ba5"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("d62ebf1b-bcfa-4062-8fb4-e04d1c003d12"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("64c0bb7d-ce23-4a5b-8c3c-0152a3489731"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("08abfa77-cf8d-4c61-bd01-3a70d4b7c4de"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        });
                });

            modelBuilder.Entity("interviewer.Data.StudentAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StudentAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
