// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using interviewer.Data;

#nullable disable

namespace interviewer.Migrations
{
    [DbContext(typeof(InterviewerDbContext))]
    [Migration("20230915125658_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "6f969a94-0480-43c5-82e6-c2cd67bed243",
                            ConcurrencyStamp = "dbdc1774-4c89-4eeb-a696-d6ab2a3e7975",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "d6729882-bbe0-487f-aaaa-e98372122c88",
                            ConcurrencyStamp = "840791c6-d504-4bd2-83a1-d8f3be3c03ad",
                            Name = "Interviewer",
                            NormalizedName = "INTERVIEWER"
                        },
                        new
                        {
                            Id = "47d42f17-2d28-44f3-935c-f2666fd1a3c9",
                            ConcurrencyStamp = "c6fc95d0-e993-4e5a-bc67-bc350c089cf2",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("interviewer.Data.Comment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepId")
                        .HasColumnType("int");

                    b.Property<string>("InterviewerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("interviewer.Data.Interviewer", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interviewers");
                });

            modelBuilder.Entity("interviewer.Data.InterviewerUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("interviewer.Data.Student", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("College")
                        .HasColumnType("int");

                    b.Property<int>("FirstDepartment")
                        .HasColumnType("int");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SecondDepartment")
                        .HasColumnType("int");

                    b.Property<string>("Skills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeChat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = "65c9b713-ff12-4281-b671-449bd948c9c1",
                            College = 7,
                            FirstDepartment = 4,
                            Grade = "PSWF12",
                            Introduction = "759440887720476616022880",
                            Name = "JYFMK2",
                            Phone = "79625123792",
                            Qq = "8618703619",
                            State = 10,
                            StudentId = "8118450142"
                        },
                        new
                        {
                            Id = "ad1b8320-4817-4515-bef4-e649781c368c",
                            College = 19,
                            FirstDepartment = 1,
                            Grade = "994TAZ",
                            Introduction = "119564072480812517814928",
                            Name = "T8GSFH",
                            Phone = "20106338527",
                            Qq = "3342137308",
                            State = 10,
                            StudentId = "7594674304"
                        },
                        new
                        {
                            Id = "d8b7ca4a-d0e8-40db-911e-9cefcc808d87",
                            College = 17,
                            FirstDepartment = 3,
                            Grade = "8PLQ4Z",
                            Introduction = "423961850273791954201992",
                            Name = "OPCGH1",
                            Phone = "19919013295",
                            Qq = "0039331934",
                            State = 10,
                            StudentId = "5780912946"
                        },
                        new
                        {
                            Id = "9aaba1a5-d3ab-434d-a465-1df5594af361",
                            College = 3,
                            FirstDepartment = 3,
                            Grade = "RVN9HZ",
                            Introduction = "830751292380190310629995",
                            Name = "R5BFUZ",
                            Phone = "41088912198",
                            Qq = "7758813005",
                            State = 10,
                            StudentId = "0574501447"
                        },
                        new
                        {
                            Id = "f04ea9a2-5a63-4593-9879-6ab39ea7e340",
                            College = 14,
                            FirstDepartment = 1,
                            Grade = "RSYU1Q",
                            Introduction = "664648852936952780352431",
                            Name = "6Q1EET",
                            Phone = "16191832112",
                            Qq = "6379434928",
                            State = 10,
                            StudentId = "9337617277"
                        },
                        new
                        {
                            Id = "3f2ce361-9f67-4cad-85dd-fd51add30f5b",
                            College = 21,
                            FirstDepartment = 2,
                            Grade = "UHE4N7",
                            Introduction = "011462648938888576815171",
                            Name = "HAJS97",
                            Phone = "27006176701",
                            Qq = "6221249066",
                            State = 10,
                            StudentId = "7549701109"
                        },
                        new
                        {
                            Id = "4f6e2d01-ea71-4046-935e-dd71b8f4c603",
                            College = 25,
                            FirstDepartment = 1,
                            Grade = "43EHXS",
                            Introduction = "773839707245492221434466",
                            Name = "1DBSNN",
                            Phone = "06398890109",
                            Qq = "9334291606",
                            State = 10,
                            StudentId = "0410147513"
                        },
                        new
                        {
                            Id = "32970ffa-5d60-42f9-ad8c-ea5aa4605168",
                            College = 7,
                            FirstDepartment = 3,
                            Grade = "ZWTBLS",
                            Introduction = "483369112728314188563636",
                            Name = "QFGRNQ",
                            Phone = "78345574588",
                            Qq = "3683367210",
                            State = 10,
                            StudentId = "6379166319"
                        },
                        new
                        {
                            Id = "b4e8a1ad-694b-4ecd-970e-58880ac942eb",
                            College = 20,
                            FirstDepartment = 3,
                            Grade = "K9SSX2",
                            Introduction = "861284176705053531024559",
                            Name = "R85RZ3",
                            Phone = "89248715877",
                            Qq = "0627861846",
                            State = 10,
                            StudentId = "1813974065"
                        },
                        new
                        {
                            Id = "54c7ae91-7206-4097-b31d-58b4efba117a",
                            College = 25,
                            FirstDepartment = 1,
                            Grade = "YAU338",
                            Introduction = "811722220538885576831906",
                            Name = "8UCRO2",
                            Phone = "18942327812",
                            Qq = "8694327624",
                            State = 10,
                            StudentId = "4894605092"
                        },
                        new
                        {
                            Id = "fcc982d8-a8a2-43b3-a346-d017e0130bf1",
                            College = 16,
                            FirstDepartment = 3,
                            Grade = "ORLNT7",
                            Introduction = "302150527560975976940524",
                            Name = "1I79N8",
                            Phone = "75520007546",
                            Qq = "2488293960",
                            State = 10,
                            StudentId = "1400202284"
                        },
                        new
                        {
                            Id = "5dbfecb1-4a97-4702-b1a4-ebaf48b58633",
                            College = 4,
                            FirstDepartment = 1,
                            Grade = "3D2JCO",
                            Introduction = "752075001493322028365058",
                            Name = "NG0QAC",
                            Phone = "80193965019",
                            Qq = "0963060892",
                            State = 10,
                            StudentId = "6398336345"
                        },
                        new
                        {
                            Id = "38c965e7-193b-4143-9409-7d9bd97ad51c",
                            College = 10,
                            FirstDepartment = 4,
                            Grade = "NDIWCU",
                            Introduction = "373756468604982464458535",
                            Name = "Z1YM5E",
                            Phone = "75193698488",
                            Qq = "5480277379",
                            State = 10,
                            StudentId = "8096801916"
                        },
                        new
                        {
                            Id = "187df503-811d-4ccc-930a-36d6a8d24047",
                            College = 7,
                            FirstDepartment = 1,
                            Grade = "HB9VUV",
                            Introduction = "581672805948828995095413",
                            Name = "RQAU4E",
                            Phone = "62933401614",
                            Qq = "3476130030",
                            State = 10,
                            StudentId = "2484421824"
                        },
                        new
                        {
                            Id = "ba2d4543-5ddd-42e5-a4e1-ffe1bd6080b7",
                            College = 18,
                            FirstDepartment = 5,
                            Grade = "W4IXM8",
                            Introduction = "586511930616945692057833",
                            Name = "IXU935",
                            Phone = "75677790906",
                            Qq = "9553084771",
                            State = 10,
                            StudentId = "2942774371"
                        },
                        new
                        {
                            Id = "d2262018-fe11-43c9-a78f-9b16146e8ce5",
                            College = 23,
                            FirstDepartment = 5,
                            Grade = "D7FGEX",
                            Introduction = "625189576491855057899274",
                            Name = "1OGQ6G",
                            Phone = "74423161149",
                            Qq = "4632369566",
                            State = 10,
                            StudentId = "4319069104"
                        },
                        new
                        {
                            Id = "efbf8271-7f34-4bf1-93a5-e441cdebe8e2",
                            College = 7,
                            FirstDepartment = 1,
                            Grade = "T4IOY0",
                            Introduction = "970703911926144556647520",
                            Name = "3EU6O7",
                            Phone = "69799552384",
                            Qq = "5681215584",
                            State = 10,
                            StudentId = "6803162443"
                        },
                        new
                        {
                            Id = "afaee1ed-f73d-417d-a904-cb541043399b",
                            College = 15,
                            FirstDepartment = 4,
                            Grade = "F77KO6",
                            Introduction = "564744268876374735250659",
                            Name = "DJFL8C",
                            Phone = "75723871743",
                            Qq = "9000954794",
                            State = 10,
                            StudentId = "4115705421"
                        },
                        new
                        {
                            Id = "069cb493-cb98-422b-8f81-3482b55b69a8",
                            College = 3,
                            FirstDepartment = 4,
                            Grade = "RWZ1W9",
                            Introduction = "987395754894788873441999",
                            Name = "OPKWA8",
                            Phone = "99768676270",
                            Qq = "7428156792",
                            State = 10,
                            StudentId = "5529441711"
                        },
                        new
                        {
                            Id = "92840ac8-74fd-4b43-9264-9bee659f9c20",
                            College = 4,
                            FirstDepartment = 3,
                            Grade = "65PK7T",
                            Introduction = "518515515978276200075774",
                            Name = "K0B4LD",
                            Phone = "66680452519",
                            Qq = "9649544011",
                            State = 10,
                            StudentId = "7311981808"
                        },
                        new
                        {
                            Id = "e3ab3456-cd7a-4d05-9b66-75862bf21ea8",
                            College = 16,
                            FirstDepartment = 1,
                            Grade = "LGW1LF",
                            Introduction = "530717632276821684054619",
                            Name = "LI5V5V",
                            Phone = "10441149557",
                            Qq = "8636145937",
                            State = 10,
                            StudentId = "3898886952"
                        },
                        new
                        {
                            Id = "a8baa4ea-2d49-4bab-a900-98859d2eafe7",
                            College = 14,
                            FirstDepartment = 1,
                            Grade = "JTGED8",
                            Introduction = "730969639673342341941377",
                            Name = "0TJUX6",
                            Phone = "91912111610",
                            Qq = "0841034941",
                            State = 10,
                            StudentId = "6164099838"
                        },
                        new
                        {
                            Id = "80671529-f38a-4ee5-830e-14540b379025",
                            College = 13,
                            FirstDepartment = 2,
                            Grade = "OQDOYZ",
                            Introduction = "693102363172424558388106",
                            Name = "RFSVET",
                            Phone = "38359088168",
                            Qq = "2257270743",
                            State = 10,
                            StudentId = "7207698412"
                        },
                        new
                        {
                            Id = "f3e6fcd7-e18b-4ec5-baa3-a6e7e7752688",
                            College = 9,
                            FirstDepartment = 2,
                            Grade = "GRGT2F",
                            Introduction = "786512594053580624175956",
                            Name = "ZH8I74",
                            Phone = "71316926567",
                            Qq = "1221734058",
                            State = 10,
                            StudentId = "0422770983"
                        },
                        new
                        {
                            Id = "cc49815c-f4bf-4cf9-98a3-69c28710ef7c",
                            College = 0,
                            FirstDepartment = 2,
                            Grade = "07E3C5",
                            Introduction = "346155228562528396140177",
                            Name = "3R6XBE",
                            Phone = "47792311658",
                            Qq = "3568394303",
                            State = 10,
                            StudentId = "1331984186"
                        },
                        new
                        {
                            Id = "dbd80029-a714-432a-abe5-5342caddd8cc",
                            College = 0,
                            FirstDepartment = 6,
                            Grade = "RSNCDC",
                            Introduction = "211109580389328282548758",
                            Name = "5XBYR3",
                            Phone = "60039155750",
                            Qq = "1456099853",
                            State = 10,
                            StudentId = "0717825697"
                        },
                        new
                        {
                            Id = "1e20001c-575d-406a-a3a7-b6f5f99d4b4c",
                            College = 12,
                            FirstDepartment = 6,
                            Grade = "OLWSCB",
                            Introduction = "516287386953380361273505",
                            Name = "X7NKQL",
                            Phone = "65970753426",
                            Qq = "5906040262",
                            State = 10,
                            StudentId = "6300673580"
                        },
                        new
                        {
                            Id = "a0825758-4f2c-4587-b45a-5a7f2fec0230",
                            College = 17,
                            FirstDepartment = 1,
                            Grade = "2EQX7L",
                            Introduction = "234107695624342928444055",
                            Name = "Y388XO",
                            Phone = "52095309761",
                            Qq = "7243982665",
                            State = 10,
                            StudentId = "8653047843"
                        },
                        new
                        {
                            Id = "56574992-51e8-4b22-ad89-1a47fa940d77",
                            College = 23,
                            FirstDepartment = 1,
                            Grade = "LJI7Y7",
                            Introduction = "212029711084474512134173",
                            Name = "JFMEXK",
                            Phone = "10661796160",
                            Qq = "8682007759",
                            State = 10,
                            StudentId = "4661875741"
                        },
                        new
                        {
                            Id = "8bfc2c52-aef3-4f74-b36c-2fd3e2cb73cf",
                            College = 2,
                            FirstDepartment = 2,
                            Grade = "EBED8A",
                            Introduction = "184239112029400879984050",
                            Name = "0T7BYT",
                            Phone = "12363908320",
                            Qq = "5204419471",
                            State = 10,
                            StudentId = "3979425388"
                        },
                        new
                        {
                            Id = "3413c7f1-8c69-42a3-9b29-43d3a6e2de96",
                            College = 22,
                            FirstDepartment = 1,
                            Grade = "X70E0C",
                            Introduction = "238070388976350680199787",
                            Name = "4VVH70",
                            Phone = "60884223826",
                            Qq = "4496627364",
                            State = 10,
                            StudentId = "2858945596"
                        },
                        new
                        {
                            Id = "1548cd1c-330c-46bf-abb0-b2d22e117298",
                            College = 1,
                            FirstDepartment = 5,
                            Grade = "TQIZLE",
                            Introduction = "438526049745164143707317",
                            Name = "N41D0M",
                            Phone = "69512972444",
                            Qq = "6857928827",
                            State = 10,
                            StudentId = "1246180280"
                        },
                        new
                        {
                            Id = "ce70638c-a9cd-4e3b-bbe6-31cb653256bc",
                            College = 17,
                            FirstDepartment = 6,
                            Grade = "UEVJOH",
                            Introduction = "343361596376308000292435",
                            Name = "NKDNLO",
                            Phone = "32335091717",
                            Qq = "8061415862",
                            State = 10,
                            StudentId = "3665116972"
                        },
                        new
                        {
                            Id = "62128959-51e8-4134-a062-de716f922c44",
                            College = 9,
                            FirstDepartment = 1,
                            Grade = "BHO5QG",
                            Introduction = "399119003194721100825118",
                            Name = "FX4KSX",
                            Phone = "24563517032",
                            Qq = "3648920496",
                            State = 10,
                            StudentId = "4580130249"
                        },
                        new
                        {
                            Id = "dc3b74c2-c68d-4250-a8ea-49752279e9c4",
                            College = 12,
                            FirstDepartment = 6,
                            Grade = "AUJRRH",
                            Introduction = "622901119700760033941646",
                            Name = "DFTRL1",
                            Phone = "59213706644",
                            Qq = "6413860590",
                            State = 10,
                            StudentId = "9330192073"
                        },
                        new
                        {
                            Id = "862f3dba-dcee-4a9f-af7a-f2c2c0554f11",
                            College = 17,
                            FirstDepartment = 2,
                            Grade = "NG6RG4",
                            Introduction = "190173917212402287735303",
                            Name = "H7GX5R",
                            Phone = "14070317241",
                            Qq = "6499619834",
                            State = 10,
                            StudentId = "5650247707"
                        },
                        new
                        {
                            Id = "fae01284-5cc4-4ac4-a232-582e3789cbcf",
                            College = 24,
                            FirstDepartment = 4,
                            Grade = "JNNO2K",
                            Introduction = "153367462388943287513428",
                            Name = "9QO4EX",
                            Phone = "98822552134",
                            Qq = "5883569768",
                            State = 10,
                            StudentId = "8948264713"
                        },
                        new
                        {
                            Id = "a26821bb-2ca6-4192-9922-0b7b0062fe11",
                            College = 3,
                            FirstDepartment = 5,
                            Grade = "14X7PZ",
                            Introduction = "865170196125736584248639",
                            Name = "SID668",
                            Phone = "47193682924",
                            Qq = "6864889952",
                            State = 10,
                            StudentId = "0230988598"
                        },
                        new
                        {
                            Id = "a5ce1730-6f1e-4252-8e63-f42167371c3c",
                            College = 19,
                            FirstDepartment = 1,
                            Grade = "WXOMBD",
                            Introduction = "203363483575238435797384",
                            Name = "AG50C1",
                            Phone = "91047592496",
                            Qq = "8713697976",
                            State = 10,
                            StudentId = "1951325317"
                        },
                        new
                        {
                            Id = "74b95ec1-e69e-497a-a52c-1a3296c73f8f",
                            College = 1,
                            FirstDepartment = 5,
                            Grade = "P6H86H",
                            Introduction = "170705611280918247682660",
                            Name = "LVGA3D",
                            Phone = "08581649127",
                            Qq = "6095819404",
                            State = 10,
                            StudentId = "5518248889"
                        },
                        new
                        {
                            Id = "da104aef-036e-4fec-934a-76ef963ee637",
                            College = 2,
                            FirstDepartment = 3,
                            Grade = "K4UMWG",
                            Introduction = "379431378050796272119608",
                            Name = "ROWBKK",
                            Phone = "16382121704",
                            Qq = "6965668560",
                            State = 10,
                            StudentId = "9809426128"
                        },
                        new
                        {
                            Id = "c302f43f-c9cb-4cfd-a71d-d3f681f91c93",
                            College = 24,
                            FirstDepartment = 2,
                            Grade = "EIEBI1",
                            Introduction = "182922001185180178524974",
                            Name = "KAV780",
                            Phone = "86173897878",
                            Qq = "3461770198",
                            State = 10,
                            StudentId = "8258159084"
                        },
                        new
                        {
                            Id = "c7f34004-1455-4671-a8f1-eadc9da11d50",
                            College = 26,
                            FirstDepartment = 6,
                            Grade = "N3LXND",
                            Introduction = "144346526646062706445028",
                            Name = "FXJ2ZU",
                            Phone = "90162000130",
                            Qq = "5190612215",
                            State = 10,
                            StudentId = "0665250382"
                        },
                        new
                        {
                            Id = "d3ecdd81-6d33-4f52-8b1c-ca1244a2314c",
                            College = 21,
                            FirstDepartment = 5,
                            Grade = "YZNBHR",
                            Introduction = "453723395892626544051137",
                            Name = "954CP4",
                            Phone = "47553197523",
                            Qq = "0440725512",
                            State = 10,
                            StudentId = "8376292672"
                        },
                        new
                        {
                            Id = "f9495ec1-eb77-4399-a853-169294aae090",
                            College = 15,
                            FirstDepartment = 1,
                            Grade = "FOYV1B",
                            Introduction = "612041735616898996862362",
                            Name = "WYE2B2",
                            Phone = "75549290098",
                            Qq = "7701370955",
                            State = 10,
                            StudentId = "3990454070"
                        },
                        new
                        {
                            Id = "b8b215b5-59ba-47dd-bb82-38527b26f999",
                            College = 0,
                            FirstDepartment = 4,
                            Grade = "3PAT0Q",
                            Introduction = "892433269251852233339057",
                            Name = "I46HD1",
                            Phone = "28266309572",
                            Qq = "2945710023",
                            State = 10,
                            StudentId = "3154906690"
                        },
                        new
                        {
                            Id = "4b1b8df1-4efa-4dda-b3fa-d296e48fec4e",
                            College = 4,
                            FirstDepartment = 1,
                            Grade = "IPP1O2",
                            Introduction = "983004551066397304918815",
                            Name = "C5T1HM",
                            Phone = "50981889877",
                            Qq = "4533973886",
                            State = 10,
                            StudentId = "5613401040"
                        },
                        new
                        {
                            Id = "31779b2d-d26b-4aec-aa26-ebbb28783f4e",
                            College = 11,
                            FirstDepartment = 1,
                            Grade = "V7USGO",
                            Introduction = "132362847405248768056643",
                            Name = "EK5ZKD",
                            Phone = "19660266525",
                            Qq = "5631555210",
                            State = 10,
                            StudentId = "1373173546"
                        },
                        new
                        {
                            Id = "955a770f-3b13-441f-8626-d9bafe942bd3",
                            College = 21,
                            FirstDepartment = 6,
                            Grade = "55IUJP",
                            Introduction = "549611097363824039007388",
                            Name = "O15F4N",
                            Phone = "46449848738",
                            Qq = "4244144966",
                            State = 10,
                            StudentId = "5519092097"
                        },
                        new
                        {
                            Id = "9635ee7d-912a-4a33-9b87-130f46f0f896",
                            College = 10,
                            FirstDepartment = 4,
                            Grade = "HOZA2C",
                            Introduction = "604321690767859997432178",
                            Name = "2EZZRF",
                            Phone = "92929078067",
                            Qq = "7555573590",
                            State = 10,
                            StudentId = "1674705277"
                        },
                        new
                        {
                            Id = "81c8574d-67f3-4b88-8ad5-23fd173d118c",
                            College = 2,
                            FirstDepartment = 6,
                            Grade = "0RFEVT",
                            Introduction = "418186883297327417911364",
                            Name = "2Y44DF",
                            Phone = "54888886576",
                            Qq = "9882993246",
                            State = 10,
                            StudentId = "1656173651"
                        },
                        new
                        {
                            Id = "16d9a969-4ca6-4b13-8fca-85dd31674a57",
                            College = 26,
                            FirstDepartment = 2,
                            Grade = "4JV9DG",
                            Introduction = "632212467216121941079416",
                            Name = "H1ERCR",
                            Phone = "27024957382",
                            Qq = "7527494613",
                            State = 10,
                            StudentId = "7387096988"
                        },
                        new
                        {
                            Id = "020a32a1-a0f2-47f0-8c3c-9f1195c79524",
                            College = 9,
                            FirstDepartment = 5,
                            Grade = "RAKRTC",
                            Introduction = "818874298532276974618296",
                            Name = "BEBJGD",
                            Phone = "14865109915",
                            Qq = "0190772823",
                            State = 10,
                            StudentId = "3596818598"
                        },
                        new
                        {
                            Id = "b6e38bda-4319-4d9c-995c-27dd1c4220ef",
                            College = 19,
                            FirstDepartment = 4,
                            Grade = "1RDS7D",
                            Introduction = "779344526629510432941173",
                            Name = "ETNZ0N",
                            Phone = "48199277805",
                            Qq = "0734836507",
                            State = 10,
                            StudentId = "9752513427"
                        },
                        new
                        {
                            Id = "079be6c4-4442-4285-923d-419ca26e3a81",
                            College = 18,
                            FirstDepartment = 2,
                            Grade = "KUOZV4",
                            Introduction = "501921503691225974515270",
                            Name = "K0201Q",
                            Phone = "36616000766",
                            Qq = "3704460235",
                            State = 10,
                            StudentId = "4969528069"
                        },
                        new
                        {
                            Id = "a5dccc17-00b2-4bd3-811c-7f66c3acd710",
                            College = 2,
                            FirstDepartment = 4,
                            Grade = "ZS4P6F",
                            Introduction = "799710353878271809454211",
                            Name = "JBBPRS",
                            Phone = "21656643961",
                            Qq = "0834753972",
                            State = 10,
                            StudentId = "2292586802"
                        },
                        new
                        {
                            Id = "7a6d5454-f923-40df-a8d8-9f6d31653975",
                            College = 23,
                            FirstDepartment = 1,
                            Grade = "NYQ165",
                            Introduction = "931195552186702058062043",
                            Name = "4ZRMRX",
                            Phone = "88301134635",
                            Qq = "0399339503",
                            State = 10,
                            StudentId = "6220026710"
                        },
                        new
                        {
                            Id = "6a4788ec-991d-47d1-bb0c-92039cfefb9b",
                            College = 5,
                            FirstDepartment = 2,
                            Grade = "8F2JIM",
                            Introduction = "009341857463675051941861",
                            Name = "4YA9VR",
                            Phone = "38319452340",
                            Qq = "4593585325",
                            State = 10,
                            StudentId = "4549628179"
                        },
                        new
                        {
                            Id = "3cad81e9-fa83-4555-9e52-74488211f2fa",
                            College = 19,
                            FirstDepartment = 2,
                            Grade = "7QDJ85",
                            Introduction = "253406658550986099216824",
                            Name = "PP8PEJ",
                            Phone = "93442419817",
                            Qq = "2659066151",
                            State = 10,
                            StudentId = "4781893130"
                        },
                        new
                        {
                            Id = "8244566f-2db6-452a-a395-5884f32d7b17",
                            College = 23,
                            FirstDepartment = 3,
                            Grade = "U5MET4",
                            Introduction = "899876453461636150073219",
                            Name = "VQQL1M",
                            Phone = "49634257196",
                            Qq = "0272599311",
                            State = 10,
                            StudentId = "9591463159"
                        },
                        new
                        {
                            Id = "4d2210d4-cd27-4819-afde-a504498cf68f",
                            College = 8,
                            FirstDepartment = 6,
                            Grade = "MQ9MQ3",
                            Introduction = "177878671969866200057477",
                            Name = "ON8O56",
                            Phone = "54778076132",
                            Qq = "9236114329",
                            State = 10,
                            StudentId = "3888949057"
                        },
                        new
                        {
                            Id = "9ebc38a8-efec-4e9b-bdc7-cebdfcd0d657",
                            College = 0,
                            FirstDepartment = 2,
                            Grade = "X5UMSE",
                            Introduction = "254832062378087425865101",
                            Name = "FFXJ0H",
                            Phone = "68825651710",
                            Qq = "6847964468",
                            State = 10,
                            StudentId = "2146032392"
                        },
                        new
                        {
                            Id = "ce7908ae-5383-4f3c-96a9-e51e25106921",
                            College = 14,
                            FirstDepartment = 5,
                            Grade = "2ZF87M",
                            Introduction = "338193084331885015604416",
                            Name = "ZB94IE",
                            Phone = "32221647710",
                            Qq = "5773090085",
                            State = 10,
                            StudentId = "9554010485"
                        },
                        new
                        {
                            Id = "5fe39bcf-766a-4264-8e25-0b9064109dbd",
                            College = 9,
                            FirstDepartment = 5,
                            Grade = "I78N6G",
                            Introduction = "845369709295631238559292",
                            Name = "I0UWGW",
                            Phone = "12290221611",
                            Qq = "1999471083",
                            State = 10,
                            StudentId = "6017816547"
                        },
                        new
                        {
                            Id = "f990f93a-c4f2-4a19-8e49-70fb2d25ec63",
                            College = 10,
                            FirstDepartment = 1,
                            Grade = "DYJ7IV",
                            Introduction = "415327294196606496752562",
                            Name = "JHI2UE",
                            Phone = "20112944676",
                            Qq = "1113847515",
                            State = 10,
                            StudentId = "5735736916"
                        },
                        new
                        {
                            Id = "978e9cdc-ab3e-426a-95ec-b88bfaf1980f",
                            College = 9,
                            FirstDepartment = 3,
                            Grade = "8SK7BP",
                            Introduction = "734312160171180382569982",
                            Name = "UZTUDW",
                            Phone = "65375047027",
                            Qq = "7346563232",
                            State = 10,
                            StudentId = "1267608523"
                        },
                        new
                        {
                            Id = "ee847be6-81de-4d11-b951-44aa0b1c295f",
                            College = 21,
                            FirstDepartment = 3,
                            Grade = "M91RFP",
                            Introduction = "051261007810378659979555",
                            Name = "KNWCKN",
                            Phone = "00020488778",
                            Qq = "5806817540",
                            State = 10,
                            StudentId = "2461373463"
                        },
                        new
                        {
                            Id = "e454518b-5f2a-41e2-9075-cc6be415622a",
                            College = 2,
                            FirstDepartment = 6,
                            Grade = "K7JF0M",
                            Introduction = "409589013785065523893968",
                            Name = "M9V61N",
                            Phone = "20116640870",
                            Qq = "9050177381",
                            State = 10,
                            StudentId = "2276132229"
                        },
                        new
                        {
                            Id = "acc71ef8-5235-40c8-b09d-89a236d31c5f",
                            College = 10,
                            FirstDepartment = 1,
                            Grade = "W9NE7O",
                            Introduction = "092500667760702684785516",
                            Name = "KJGXC1",
                            Phone = "56326739321",
                            Qq = "0132875976",
                            State = 10,
                            StudentId = "4349627522"
                        },
                        new
                        {
                            Id = "33761a2e-13a9-487d-818b-923cf4a3dee4",
                            College = 23,
                            FirstDepartment = 4,
                            Grade = "0VWLYW",
                            Introduction = "966642416469301433569404",
                            Name = "3A916D",
                            Phone = "25422869130",
                            Qq = "7005615273",
                            State = 10,
                            StudentId = "7004034263"
                        },
                        new
                        {
                            Id = "7ac8e76d-637f-438c-a90e-de2d52c2300e",
                            College = 14,
                            FirstDepartment = 1,
                            Grade = "LYY3U4",
                            Introduction = "159548834057533725011872",
                            Name = "NUIJO1",
                            Phone = "26434843527",
                            Qq = "8494055976",
                            State = 10,
                            StudentId = "0877145704"
                        },
                        new
                        {
                            Id = "9c4f72af-adf4-487c-82df-d2a8340e649b",
                            College = 6,
                            FirstDepartment = 5,
                            Grade = "PL3KFF",
                            Introduction = "806254377499473167205676",
                            Name = "DSIF2E",
                            Phone = "71877861575",
                            Qq = "3119008077",
                            State = 10,
                            StudentId = "8627483893"
                        },
                        new
                        {
                            Id = "18d4a90c-1557-4914-bf37-807a7dcb5aaa",
                            College = 10,
                            FirstDepartment = 3,
                            Grade = "H052EO",
                            Introduction = "383692053186399989941612",
                            Name = "986HTX",
                            Phone = "51543442220",
                            Qq = "7541554740",
                            State = 10,
                            StudentId = "8943512864"
                        },
                        new
                        {
                            Id = "a83e388d-b8fe-4c90-871c-cbb785c321ac",
                            College = 5,
                            FirstDepartment = 6,
                            Grade = "T0DJ02",
                            Introduction = "544509836592622243812674",
                            Name = "KW6T72",
                            Phone = "68359558002",
                            Qq = "0721195151",
                            State = 10,
                            StudentId = "5112858273"
                        },
                        new
                        {
                            Id = "655450f5-f33b-4a35-910d-60c407e3b388",
                            College = 4,
                            FirstDepartment = 1,
                            Grade = "YUB0CI",
                            Introduction = "044493962262442511092611",
                            Name = "FUXOIX",
                            Phone = "34498747007",
                            Qq = "5897031453",
                            State = 10,
                            StudentId = "2357654436"
                        },
                        new
                        {
                            Id = "460b6523-7bcc-478b-b7b1-9f499fb2a66f",
                            College = 7,
                            FirstDepartment = 1,
                            Grade = "8HWLPD",
                            Introduction = "232871565622961424171573",
                            Name = "NVW8BQ",
                            Phone = "38885130656",
                            Qq = "2940100630",
                            State = 10,
                            StudentId = "7784009904"
                        },
                        new
                        {
                            Id = "0f684c56-5cfa-4d50-9e5d-77a368e4c928",
                            College = 18,
                            FirstDepartment = 6,
                            Grade = "TDUINA",
                            Introduction = "937806942085989985539106",
                            Name = "ZYKSCG",
                            Phone = "08443905328",
                            Qq = "4537342505",
                            State = 10,
                            StudentId = "1612679828"
                        },
                        new
                        {
                            Id = "45b8d3a7-43ca-44f4-9e39-62feeb50dd2c",
                            College = 3,
                            FirstDepartment = 4,
                            Grade = "S0ZNY1",
                            Introduction = "840430537421176787612350",
                            Name = "QEH3Q1",
                            Phone = "61182767449",
                            Qq = "6557123267",
                            State = 10,
                            StudentId = "1793617991"
                        },
                        new
                        {
                            Id = "f07ba120-04d4-4403-822f-686563293b52",
                            College = 3,
                            FirstDepartment = 1,
                            Grade = "UMB4IL",
                            Introduction = "482364039473080021624535",
                            Name = "72PC1D",
                            Phone = "68981153552",
                            Qq = "9472314595",
                            State = 10,
                            StudentId = "6533099406"
                        },
                        new
                        {
                            Id = "d9e007c0-014f-47c7-811b-ffd044b8c91d",
                            College = 6,
                            FirstDepartment = 3,
                            Grade = "SOZMTP",
                            Introduction = "663937956432230132193956",
                            Name = "C668VB",
                            Phone = "22205659091",
                            Qq = "0675785407",
                            State = 10,
                            StudentId = "9728585795"
                        },
                        new
                        {
                            Id = "27dbca16-404d-4c64-8092-3bcaab0c1cd3",
                            College = 19,
                            FirstDepartment = 6,
                            Grade = "E3ZDK8",
                            Introduction = "031352702716113599639337",
                            Name = "A9GGRQ",
                            Phone = "62664535198",
                            Qq = "9974183999",
                            State = 10,
                            StudentId = "5473757486"
                        },
                        new
                        {
                            Id = "3c99c018-ebef-4d62-a660-dd0810c7b22b",
                            College = 18,
                            FirstDepartment = 2,
                            Grade = "YHNHDR",
                            Introduction = "916579769166651595365545",
                            Name = "9AXIDO",
                            Phone = "47765680523",
                            Qq = "2603539064",
                            State = 10,
                            StudentId = "9016688178"
                        },
                        new
                        {
                            Id = "b9970793-6f9f-43d5-8499-e09355544fad",
                            College = 16,
                            FirstDepartment = 1,
                            Grade = "3MEISS",
                            Introduction = "192356380679108616679436",
                            Name = "2GO6ZF",
                            Phone = "08843747447",
                            Qq = "4973567288",
                            State = 10,
                            StudentId = "0188211877"
                        },
                        new
                        {
                            Id = "83468b51-c397-4422-b61b-0e600f3ad821",
                            College = 7,
                            FirstDepartment = 5,
                            Grade = "RI1QGN",
                            Introduction = "874556406937115642801125",
                            Name = "BFQ2NL",
                            Phone = "88479523434",
                            Qq = "2948109478",
                            State = 10,
                            StudentId = "6834795291"
                        },
                        new
                        {
                            Id = "2d08a3d2-c3ca-45a4-9a73-0579598b9fef",
                            College = 6,
                            FirstDepartment = 6,
                            Grade = "QH1BOF",
                            Introduction = "773441208053903125276724",
                            Name = "GOPDY2",
                            Phone = "13516285983",
                            Qq = "8918058612",
                            State = 10,
                            StudentId = "3019223966"
                        },
                        new
                        {
                            Id = "a6bf2c88-c92c-4772-ba97-a0f98742430e",
                            College = 9,
                            FirstDepartment = 1,
                            Grade = "YANRPG",
                            Introduction = "022665061854950991333766",
                            Name = "FMM8Y5",
                            Phone = "25499672161",
                            Qq = "2077939808",
                            State = 10,
                            StudentId = "2947721518"
                        },
                        new
                        {
                            Id = "118c613a-a771-4fbd-96c7-2f6688ba7470",
                            College = 7,
                            FirstDepartment = 3,
                            Grade = "KQHYW3",
                            Introduction = "010734189222066919606992",
                            Name = "M2K8VH",
                            Phone = "77037242027",
                            Qq = "1790647040",
                            State = 10,
                            StudentId = "8860366363"
                        },
                        new
                        {
                            Id = "6f30ba45-8cb6-4a9b-a655-ff2c3ab322c7",
                            College = 13,
                            FirstDepartment = 2,
                            Grade = "PAHPKC",
                            Introduction = "598236679060371090514586",
                            Name = "6HY3XN",
                            Phone = "03103469702",
                            Qq = "6342702822",
                            State = 10,
                            StudentId = "8960745928"
                        },
                        new
                        {
                            Id = "bd7f02b0-64af-4687-96b7-c46dcc5051f0",
                            College = 15,
                            FirstDepartment = 4,
                            Grade = "4Y9TWA",
                            Introduction = "630331325585183186390300",
                            Name = "L4MJ6C",
                            Phone = "05670718836",
                            Qq = "0267402251",
                            State = 10,
                            StudentId = "4921188658"
                        },
                        new
                        {
                            Id = "0b850039-9ad0-4c57-8d7e-f95435b21b39",
                            College = 16,
                            FirstDepartment = 2,
                            Grade = "AZ2K4B",
                            Introduction = "252778956137852044929564",
                            Name = "TL438K",
                            Phone = "68431933350",
                            Qq = "9443940204",
                            State = 10,
                            StudentId = "5214539271"
                        },
                        new
                        {
                            Id = "3da715f4-907f-4888-aaeb-3a61b640de01",
                            College = 24,
                            FirstDepartment = 2,
                            Grade = "3QN1TU",
                            Introduction = "311743802988666258574998",
                            Name = "E1N9X3",
                            Phone = "22303999800",
                            Qq = "9006826436",
                            State = 10,
                            StudentId = "8754045558"
                        },
                        new
                        {
                            Id = "5fd1c9db-ae30-4285-8725-9726baec3ea9",
                            College = 13,
                            FirstDepartment = 1,
                            Grade = "8MHOO2",
                            Introduction = "866560812006017724182113",
                            Name = "O01ZY1",
                            Phone = "89436775850",
                            Qq = "6877624485",
                            State = 10,
                            StudentId = "8460051480"
                        },
                        new
                        {
                            Id = "a14c0c30-5100-4e98-b7c3-3398cea56af5",
                            College = 24,
                            FirstDepartment = 5,
                            Grade = "EDKT8M",
                            Introduction = "261488420479098390083633",
                            Name = "CC5GNM",
                            Phone = "49699436731",
                            Qq = "4730178747",
                            State = 10,
                            StudentId = "0265647708"
                        },
                        new
                        {
                            Id = "b383997e-b25d-4e50-96b0-e7ab720e3d58",
                            College = 19,
                            FirstDepartment = 3,
                            Grade = "AIM66W",
                            Introduction = "929907250898142471574055",
                            Name = "WQ7Y47",
                            Phone = "45815960625",
                            Qq = "7115656835",
                            State = 10,
                            StudentId = "6639653781"
                        },
                        new
                        {
                            Id = "d4b2a20e-ee5c-4e9f-ad13-ce267f9860bf",
                            College = 12,
                            FirstDepartment = 2,
                            Grade = "4HAC4V",
                            Introduction = "248793000742994364917356",
                            Name = "GTP78B",
                            Phone = "52596519160",
                            Qq = "4070531215",
                            State = 10,
                            StudentId = "7813648602"
                        },
                        new
                        {
                            Id = "d4b397a5-6958-45b0-8aba-3e25678f1daf",
                            College = 0,
                            FirstDepartment = 6,
                            Grade = "5QQKTT",
                            Introduction = "605500045566203469148386",
                            Name = "7VTJUD",
                            Phone = "95904159066",
                            Qq = "3062966558",
                            State = 10,
                            StudentId = "3856886793"
                        },
                        new
                        {
                            Id = "9aa2a878-629c-4009-8343-d8928b70125e",
                            College = 6,
                            FirstDepartment = 2,
                            Grade = "G55IYB",
                            Introduction = "274590470412930822541852",
                            Name = "BS5K2C",
                            Phone = "37406773353",
                            Qq = "3994160690",
                            State = 10,
                            StudentId = "9711986988"
                        },
                        new
                        {
                            Id = "24cfc59c-1abb-4f34-92ed-b663115df507",
                            College = 25,
                            FirstDepartment = 3,
                            Grade = "74ZJSS",
                            Introduction = "102351674037737208975329",
                            Name = "VZ3U1X",
                            Phone = "34824102532",
                            Qq = "7955843961",
                            State = 10,
                            StudentId = "3728133642"
                        },
                        new
                        {
                            Id = "4c06e042-2877-43f1-bfd3-edab0dde4170",
                            College = 17,
                            FirstDepartment = 6,
                            Grade = "SLTAIL",
                            Introduction = "956679812106911944872349",
                            Name = "NL8A8I",
                            Phone = "98766918525",
                            Qq = "9244889183",
                            State = 10,
                            StudentId = "3828525829"
                        },
                        new
                        {
                            Id = "9ecbd1aa-0783-480f-bab8-ada8bfe5bb85",
                            College = 8,
                            FirstDepartment = 5,
                            Grade = "840RU9",
                            Introduction = "337819951673983208465226",
                            Name = "WKGVCB",
                            Phone = "27580567975",
                            Qq = "4611698666",
                            State = 10,
                            StudentId = "1116340902"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("interviewer.Data.InterviewerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("interviewer.Data.InterviewerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("interviewer.Data.InterviewerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("interviewer.Data.InterviewerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
