// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using interviewer.Data;

#nullable disable

namespace interviewer.Migrations
{
    [DbContext(typeof(InterviewerDbContext))]
    [Migration("20230916160001_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b3621b98-6e9f-4f27-9968-d8109f634285",
                            ConcurrencyStamp = "24ce2a9c-e5fc-4704-8b38-5c0f8980ba76",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "e90e669d-94d4-4205-9f6e-f478746cbc38",
                            ConcurrencyStamp = "8400538c-1bd5-4ffb-ae95-cf262507c19d",
                            Name = "Interviewer",
                            NormalizedName = "INTERVIEWER"
                        },
                        new
                        {
                            Id = "f0ab04eb-29b9-4d71-9205-63b8d439154c",
                            ConcurrencyStamp = "d2a94451-a634-4d19-acd0-1bd319b5720b",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("interviewer.Data.Comment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepId")
                        .HasColumnType("int");

                    b.Property<string>("InterviewerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("StudentUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("interviewer.Data.Interviewer", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interviewers");
                });

            modelBuilder.Entity("interviewer.Data.InterviewerUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("interviewer.Data.Student", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("College")
                        .HasColumnType("int");

                    b.Property<int>("FirstDepartment")
                        .HasColumnType("int");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SecondDepartment")
                        .HasColumnType("int");

                    b.Property<string>("Skills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeChat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = "e3d5fa5c-ab22-41f7-af0e-a5344aac8257",
                            College = 19,
                            FirstDepartment = 5,
                            Grade = "XZRPNP",
                            Introduction = "392284062857129029789813",
                            Name = "Z6OO1M",
                            Phone = "26773162891",
                            Qq = "2583528310",
                            State = 10,
                            StudentNumber = "8713329767"
                        },
                        new
                        {
                            Id = "ea0895fb-cc13-4db2-baa7-78d57d682fd9",
                            College = 16,
                            FirstDepartment = 6,
                            Grade = "BDWTRW",
                            Introduction = "956472920531887399969507",
                            Name = "KHXOPA",
                            Phone = "40995006029",
                            Qq = "2538979194",
                            State = 10,
                            StudentNumber = "9951156402"
                        },
                        new
                        {
                            Id = "26679ebe-54c4-4887-8f0c-6f570a7f1808",
                            College = 11,
                            FirstDepartment = 5,
                            Grade = "UTGRTL",
                            Introduction = "776987870866983542845841",
                            Name = "Q5YZB6",
                            Phone = "32651714812",
                            Qq = "3707170689",
                            State = 10,
                            StudentNumber = "8117272171"
                        },
                        new
                        {
                            Id = "a411f2f8-2cb3-4af2-8059-f41c580b5130",
                            College = 23,
                            FirstDepartment = 2,
                            Grade = "R6JCD4",
                            Introduction = "631865956715515452771813",
                            Name = "LNCW77",
                            Phone = "55990993659",
                            Qq = "0311048024",
                            State = 10,
                            StudentNumber = "1895440309"
                        },
                        new
                        {
                            Id = "bda50dec-66b8-4de5-a4f5-465da3c7cfb0",
                            College = 15,
                            FirstDepartment = 1,
                            Grade = "WGC1RC",
                            Introduction = "252094407462939157524265",
                            Name = "IE9K5T",
                            Phone = "31531868435",
                            Qq = "3318448970",
                            State = 10,
                            StudentNumber = "5343189857"
                        },
                        new
                        {
                            Id = "55f5b8b4-11d5-4f68-a8eb-89b67112b76a",
                            College = 5,
                            FirstDepartment = 2,
                            Grade = "8PMYFB",
                            Introduction = "659789408329741329964830",
                            Name = "ADKK1L",
                            Phone = "76232760458",
                            Qq = "1369367866",
                            State = 10,
                            StudentNumber = "1067570446"
                        },
                        new
                        {
                            Id = "b44911c7-b03c-461b-bd82-2b3d4e4d724f",
                            College = 12,
                            FirstDepartment = 6,
                            Grade = "MPAXZ4",
                            Introduction = "857437036182516877747482",
                            Name = "URBA8F",
                            Phone = "13257140509",
                            Qq = "2080408309",
                            State = 10,
                            StudentNumber = "5473016374"
                        },
                        new
                        {
                            Id = "02738e33-6ec0-4310-a87a-cb6484485a8d",
                            College = 7,
                            FirstDepartment = 3,
                            Grade = "9A49JO",
                            Introduction = "724286873233558755714071",
                            Name = "CF652Z",
                            Phone = "76656803691",
                            Qq = "7288378396",
                            State = 10,
                            StudentNumber = "6640472706"
                        },
                        new
                        {
                            Id = "7f5eaf09-4938-4d03-8f52-5cf5e392c09c",
                            College = 11,
                            FirstDepartment = 3,
                            Grade = "JA2I9X",
                            Introduction = "473824735564329293978137",
                            Name = "3WVYAC",
                            Phone = "89870019424",
                            Qq = "3823252886",
                            State = 10,
                            StudentNumber = "0761730871"
                        },
                        new
                        {
                            Id = "faf7de1f-5e09-4d77-83eb-e17499a2a14a",
                            College = 18,
                            FirstDepartment = 1,
                            Grade = "9GYG6S",
                            Introduction = "841202779749063476246100",
                            Name = "EJI6A1",
                            Phone = "72218391119",
                            Qq = "0177481353",
                            State = 10,
                            StudentNumber = "9539512339"
                        },
                        new
                        {
                            Id = "f7edc7a0-2ab1-4d17-b57b-06dddc5296e8",
                            College = 9,
                            FirstDepartment = 5,
                            Grade = "WG1FJZ",
                            Introduction = "367464140335153136979032",
                            Name = "HYOU8Q",
                            Phone = "92015675075",
                            Qq = "4135835690",
                            State = 10,
                            StudentNumber = "0316553487"
                        },
                        new
                        {
                            Id = "90cbb824-cb1e-4c9e-8611-91448d2e5d44",
                            College = 23,
                            FirstDepartment = 4,
                            Grade = "3LEUXB",
                            Introduction = "130484891035323648336794",
                            Name = "2X840P",
                            Phone = "38479255551",
                            Qq = "8872821470",
                            State = 10,
                            StudentNumber = "4612313839"
                        },
                        new
                        {
                            Id = "489da1ea-cf7a-4b86-a289-2e5be22f2c7f",
                            College = 5,
                            FirstDepartment = 3,
                            Grade = "YHUTZ7",
                            Introduction = "102186539704749352918627",
                            Name = "8EGV80",
                            Phone = "08665844594",
                            Qq = "5109240537",
                            State = 10,
                            StudentNumber = "0867506541"
                        },
                        new
                        {
                            Id = "d4bbde5c-971c-4d6b-9715-63a4cee71afb",
                            College = 23,
                            FirstDepartment = 1,
                            Grade = "Q8W9H7",
                            Introduction = "985033188073080346557058",
                            Name = "HR9RO6",
                            Phone = "19321812953",
                            Qq = "0906626046",
                            State = 10,
                            StudentNumber = "2340387446"
                        },
                        new
                        {
                            Id = "bef88de7-01b6-40d6-90de-b5642e718859",
                            College = 5,
                            FirstDepartment = 5,
                            Grade = "IN0Y16",
                            Introduction = "164708410522496546783715",
                            Name = "UHFTOK",
                            Phone = "83135116833",
                            Qq = "4312091491",
                            State = 10,
                            StudentNumber = "1028820096"
                        },
                        new
                        {
                            Id = "52585c5f-ebd3-4756-89be-340e9260e71d",
                            College = 26,
                            FirstDepartment = 4,
                            Grade = "G746K0",
                            Introduction = "010276630288893115731544",
                            Name = "5I24VC",
                            Phone = "79362580066",
                            Qq = "9809065064",
                            State = 10,
                            StudentNumber = "5743281955"
                        },
                        new
                        {
                            Id = "ea20776d-d73c-427d-b609-c0e93f0216a6",
                            College = 9,
                            FirstDepartment = 6,
                            Grade = "I6NXUV",
                            Introduction = "710939951405314398338246",
                            Name = "OQSRQ4",
                            Phone = "09040951501",
                            Qq = "4894213954",
                            State = 10,
                            StudentNumber = "1065264165"
                        },
                        new
                        {
                            Id = "193677e4-8de6-421e-a35e-735d92aa8167",
                            College = 7,
                            FirstDepartment = 2,
                            Grade = "Z1UP5K",
                            Introduction = "091145597832892734819410",
                            Name = "4NW0HV",
                            Phone = "58350409282",
                            Qq = "7685055030",
                            State = 10,
                            StudentNumber = "2096399946"
                        },
                        new
                        {
                            Id = "5771cb53-eed5-4e58-8d0a-ce8af10091c3",
                            College = 8,
                            FirstDepartment = 4,
                            Grade = "MEP71F",
                            Introduction = "202350208878412887304659",
                            Name = "7EA6J0",
                            Phone = "13332313268",
                            Qq = "0745545961",
                            State = 10,
                            StudentNumber = "2665870701"
                        },
                        new
                        {
                            Id = "8063318c-611e-4504-acd9-7dbbe3561e14",
                            College = 20,
                            FirstDepartment = 2,
                            Grade = "03PJP0",
                            Introduction = "976902666228983019431642",
                            Name = "Y9K18B",
                            Phone = "13073353330",
                            Qq = "5418759196",
                            State = 10,
                            StudentNumber = "2525294860"
                        },
                        new
                        {
                            Id = "7fb7cde2-b9db-48c4-8be1-82ce000dfd5b",
                            College = 15,
                            FirstDepartment = 4,
                            Grade = "10HUSM",
                            Introduction = "112691861681937524506101",
                            Name = "IAVGYM",
                            Phone = "25776015685",
                            Qq = "0169957309",
                            State = 10,
                            StudentNumber = "0021638806"
                        },
                        new
                        {
                            Id = "f715d2e1-6dc7-4dba-890e-ca8beddf6335",
                            College = 22,
                            FirstDepartment = 2,
                            Grade = "3F97JT",
                            Introduction = "181940236478726953576301",
                            Name = "XCEW6W",
                            Phone = "65065937593",
                            Qq = "1526790552",
                            State = 10,
                            StudentNumber = "2922461557"
                        },
                        new
                        {
                            Id = "635c4228-19e7-4e4d-9931-2d9bb40735cb",
                            College = 21,
                            FirstDepartment = 4,
                            Grade = "OFOOMB",
                            Introduction = "408505841669635274422407",
                            Name = "9KG83M",
                            Phone = "92374143477",
                            Qq = "0879393410",
                            State = 10,
                            StudentNumber = "2524911621"
                        },
                        new
                        {
                            Id = "c2255ec1-0de4-4b64-8ced-8cdaa1931758",
                            College = 11,
                            FirstDepartment = 2,
                            Grade = "SD2ULS",
                            Introduction = "812979848130432490190640",
                            Name = "8LUPQ6",
                            Phone = "25852286206",
                            Qq = "8103052914",
                            State = 10,
                            StudentNumber = "2177007657"
                        },
                        new
                        {
                            Id = "efb4ed24-59db-4c53-94f8-f42cb5f7dd7f",
                            College = 19,
                            FirstDepartment = 3,
                            Grade = "3AJRBC",
                            Introduction = "069469294911351565411389",
                            Name = "1ORDEC",
                            Phone = "17959031721",
                            Qq = "0148995891",
                            State = 10,
                            StudentNumber = "4450331784"
                        },
                        new
                        {
                            Id = "20c47d0c-1b6b-4525-bb06-6bb7df0c7687",
                            College = 8,
                            FirstDepartment = 5,
                            Grade = "8EG9XW",
                            Introduction = "107853234425401003886181",
                            Name = "0MJCGU",
                            Phone = "21071236395",
                            Qq = "0167484531",
                            State = 10,
                            StudentNumber = "9202567717"
                        },
                        new
                        {
                            Id = "fc362b41-a3b7-4ab0-9fdd-3372bbec1e91",
                            College = 23,
                            FirstDepartment = 2,
                            Grade = "5MKDH0",
                            Introduction = "613514968640738773128453",
                            Name = "3OI74A",
                            Phone = "02548122997",
                            Qq = "8935543605",
                            State = 10,
                            StudentNumber = "4034796723"
                        },
                        new
                        {
                            Id = "b6126d5f-ac4f-466f-83bb-6ed41e1f9997",
                            College = 15,
                            FirstDepartment = 2,
                            Grade = "0GSQC1",
                            Introduction = "088345348450664182985858",
                            Name = "3OC1HU",
                            Phone = "50595498531",
                            Qq = "1068139106",
                            State = 10,
                            StudentNumber = "6953713792"
                        },
                        new
                        {
                            Id = "6d25e8bc-2af3-44a2-a8ff-efa9ed2a21e1",
                            College = 2,
                            FirstDepartment = 4,
                            Grade = "NGZDYC",
                            Introduction = "451401996846125686886273",
                            Name = "93ZIAF",
                            Phone = "91361873132",
                            Qq = "9641664534",
                            State = 10,
                            StudentNumber = "4851219007"
                        },
                        new
                        {
                            Id = "5e5134ea-2023-4666-9bf1-f76846591df8",
                            College = 7,
                            FirstDepartment = 1,
                            Grade = "KUTK1K",
                            Introduction = "737119172486145515337790",
                            Name = "LB44MT",
                            Phone = "18159456616",
                            Qq = "1640083205",
                            State = 10,
                            StudentNumber = "2118926090"
                        },
                        new
                        {
                            Id = "1763e28e-9ac1-4df6-aab9-421163586298",
                            College = 7,
                            FirstDepartment = 6,
                            Grade = "U9JYYA",
                            Introduction = "632946659932009397307968",
                            Name = "TJ3D29",
                            Phone = "99711614936",
                            Qq = "7485403694",
                            State = 10,
                            StudentNumber = "3493918751"
                        },
                        new
                        {
                            Id = "c694b887-54af-404b-ade8-7fec758964b4",
                            College = 20,
                            FirstDepartment = 3,
                            Grade = "4FKMJD",
                            Introduction = "022614764633430430614027",
                            Name = "4A67EC",
                            Phone = "98520135557",
                            Qq = "8981483665",
                            State = 10,
                            StudentNumber = "7707919910"
                        },
                        new
                        {
                            Id = "4145b599-3e51-45ad-b902-5b423adfdbd4",
                            College = 20,
                            FirstDepartment = 2,
                            Grade = "2L77NG",
                            Introduction = "804358876052996819094239",
                            Name = "Y24G6B",
                            Phone = "52980988585",
                            Qq = "4358868362",
                            State = 10,
                            StudentNumber = "2690112289"
                        },
                        new
                        {
                            Id = "2f087ae3-525c-47b7-8e6c-9d43f49d6531",
                            College = 18,
                            FirstDepartment = 3,
                            Grade = "SSGZR9",
                            Introduction = "178478393672261400870603",
                            Name = "CGMZG8",
                            Phone = "22623806341",
                            Qq = "5455843923",
                            State = 10,
                            StudentNumber = "8106007628"
                        },
                        new
                        {
                            Id = "bc6764bd-996a-4c66-811f-3ebdb2067df5",
                            College = 19,
                            FirstDepartment = 5,
                            Grade = "R696YF",
                            Introduction = "665764210937010516430589",
                            Name = "7WD09A",
                            Phone = "42963580091",
                            Qq = "8036551478",
                            State = 10,
                            StudentNumber = "4079742416"
                        },
                        new
                        {
                            Id = "ff060c8e-2a29-4cf9-8c2d-3101a17554dd",
                            College = 1,
                            FirstDepartment = 4,
                            Grade = "2GVLDL",
                            Introduction = "315388729876386174632794",
                            Name = "PMQDIW",
                            Phone = "34190729692",
                            Qq = "4356300442",
                            State = 10,
                            StudentNumber = "1112845842"
                        },
                        new
                        {
                            Id = "b17875c7-63dc-4eb4-b39b-f05ae5e4be39",
                            College = 13,
                            FirstDepartment = 5,
                            Grade = "QJ6TQF",
                            Introduction = "757741539082542895751591",
                            Name = "GDAJAC",
                            Phone = "98499972110",
                            Qq = "5094851726",
                            State = 10,
                            StudentNumber = "8476675135"
                        },
                        new
                        {
                            Id = "1d783dc9-e53d-42df-9be4-1f03067da7b3",
                            College = 26,
                            FirstDepartment = 6,
                            Grade = "Z7WJKL",
                            Introduction = "033034886364231252323873",
                            Name = "PHI5AO",
                            Phone = "18769909898",
                            Qq = "7776624617",
                            State = 10,
                            StudentNumber = "9436281226"
                        },
                        new
                        {
                            Id = "86b14ee6-af79-4aea-b55a-3d901cba7d3b",
                            College = 22,
                            FirstDepartment = 5,
                            Grade = "EMKMA5",
                            Introduction = "977899823495732931022901",
                            Name = "IZ31GR",
                            Phone = "60579968632",
                            Qq = "9710751649",
                            State = 10,
                            StudentNumber = "8329374308"
                        },
                        new
                        {
                            Id = "27d27ce7-dbde-42b5-b5ab-24de6bae9315",
                            College = 2,
                            FirstDepartment = 5,
                            Grade = "TV7UR7",
                            Introduction = "302187847497026003772853",
                            Name = "BJ35AQ",
                            Phone = "09702074145",
                            Qq = "6967729854",
                            State = 10,
                            StudentNumber = "8260480602"
                        },
                        new
                        {
                            Id = "24db3206-cda9-42aa-8e4a-fa685ea2bbb6",
                            College = 5,
                            FirstDepartment = 6,
                            Grade = "VPCB6T",
                            Introduction = "086745315554602600477695",
                            Name = "AZ1SAF",
                            Phone = "29309184530",
                            Qq = "8718433297",
                            State = 10,
                            StudentNumber = "3854257836"
                        },
                        new
                        {
                            Id = "582ddd17-f48b-412c-82f0-81e94647c943",
                            College = 25,
                            FirstDepartment = 4,
                            Grade = "UEAA91",
                            Introduction = "614646268061587239866380",
                            Name = "7TEZ4B",
                            Phone = "97132703370",
                            Qq = "8490104961",
                            State = 10,
                            StudentNumber = "0328287490"
                        },
                        new
                        {
                            Id = "07613f49-a183-4946-9812-3168062b50cd",
                            College = 19,
                            FirstDepartment = 5,
                            Grade = "Z6N6YY",
                            Introduction = "925702325858299163972401",
                            Name = "2DWD0I",
                            Phone = "96747241467",
                            Qq = "0759501805",
                            State = 10,
                            StudentNumber = "0300928823"
                        },
                        new
                        {
                            Id = "078e9860-2a4d-43b9-9c2e-f65b87b0fc1d",
                            College = 24,
                            FirstDepartment = 3,
                            Grade = "ROP0WI",
                            Introduction = "910695666223603582699790",
                            Name = "6Q35EQ",
                            Phone = "23693681439",
                            Qq = "6309603755",
                            State = 10,
                            StudentNumber = "2242852890"
                        },
                        new
                        {
                            Id = "9df7f130-e381-41c7-8203-8f69da4aa30e",
                            College = 22,
                            FirstDepartment = 1,
                            Grade = "SWNNI3",
                            Introduction = "185391047298834805588829",
                            Name = "T8QQ4P",
                            Phone = "92536928845",
                            Qq = "1004258311",
                            State = 10,
                            StudentNumber = "0581188103"
                        },
                        new
                        {
                            Id = "56567f89-071a-4868-9f18-c400696f54c3",
                            College = 15,
                            FirstDepartment = 1,
                            Grade = "BCOVQH",
                            Introduction = "606695616875897757457597",
                            Name = "U4WDLB",
                            Phone = "53130143519",
                            Qq = "9836460117",
                            State = 10,
                            StudentNumber = "8668599684"
                        },
                        new
                        {
                            Id = "44e3d5ff-3614-40c0-ace2-3bb976ef637d",
                            College = 6,
                            FirstDepartment = 3,
                            Grade = "E3TGXN",
                            Introduction = "308835991196901882038326",
                            Name = "HU6WYR",
                            Phone = "58256952378",
                            Qq = "4546508508",
                            State = 10,
                            StudentNumber = "1763385712"
                        },
                        new
                        {
                            Id = "3cbda965-1b96-4b62-a7c3-4fef98c1bd50",
                            College = 5,
                            FirstDepartment = 5,
                            Grade = "VEQCGE",
                            Introduction = "946164087464060338767516",
                            Name = "B8TER9",
                            Phone = "19990807843",
                            Qq = "4032965772",
                            State = 10,
                            StudentNumber = "1251681754"
                        },
                        new
                        {
                            Id = "40d53478-69ef-4241-b7c5-791289976a6a",
                            College = 24,
                            FirstDepartment = 6,
                            Grade = "JVELLO",
                            Introduction = "447889408750847032971863",
                            Name = "JUNXIP",
                            Phone = "56450378413",
                            Qq = "9162360816",
                            State = 10,
                            StudentNumber = "8061993173"
                        },
                        new
                        {
                            Id = "d4b9fe61-89c4-4491-9bdc-16976487c6e8",
                            College = 16,
                            FirstDepartment = 3,
                            Grade = "XYS6KH",
                            Introduction = "400218861412167536317978",
                            Name = "1AS3WI",
                            Phone = "18419701135",
                            Qq = "2565903962",
                            State = 10,
                            StudentNumber = "2722636911"
                        },
                        new
                        {
                            Id = "f25e3cfd-b528-40fb-bc45-16920922a772",
                            College = 10,
                            FirstDepartment = 1,
                            Grade = "BL7QNW",
                            Introduction = "048318877332746339188513",
                            Name = "6KMM7N",
                            Phone = "52540739834",
                            Qq = "0520028441",
                            State = 10,
                            StudentNumber = "5770157426"
                        },
                        new
                        {
                            Id = "7153d6f6-b811-47f1-b6d9-bc6893cd38f3",
                            College = 7,
                            FirstDepartment = 4,
                            Grade = "3CPU81",
                            Introduction = "970052753938604014435629",
                            Name = "GTQ3FU",
                            Phone = "17255678338",
                            Qq = "7913780134",
                            State = 10,
                            StudentNumber = "0376741043"
                        },
                        new
                        {
                            Id = "071ac596-21cb-415e-9644-108bc42c9293",
                            College = 9,
                            FirstDepartment = 1,
                            Grade = "RF9SD2",
                            Introduction = "900900247541540315848832",
                            Name = "PR1190",
                            Phone = "20103580997",
                            Qq = "7959764856",
                            State = 10,
                            StudentNumber = "4813407240"
                        },
                        new
                        {
                            Id = "2f931127-ac2d-450a-b1c4-483d938fd854",
                            College = 16,
                            FirstDepartment = 2,
                            Grade = "8Z3SIO",
                            Introduction = "438421503541598529746959",
                            Name = "YWDN19",
                            Phone = "91369691289",
                            Qq = "6077599330",
                            State = 10,
                            StudentNumber = "7507745614"
                        },
                        new
                        {
                            Id = "6a01f0ca-3673-4c33-af2a-5caa081ac125",
                            College = 0,
                            FirstDepartment = 3,
                            Grade = "QLTZPR",
                            Introduction = "497000928972394146913569",
                            Name = "C379KX",
                            Phone = "08578655549",
                            Qq = "0389651473",
                            State = 10,
                            StudentNumber = "1007684869"
                        },
                        new
                        {
                            Id = "dfae4bcc-aa81-4228-be90-bbb46e10c084",
                            College = 12,
                            FirstDepartment = 3,
                            Grade = "C0QVHN",
                            Introduction = "679695398857921111367506",
                            Name = "3XO891",
                            Phone = "76043844601",
                            Qq = "3742975158",
                            State = 10,
                            StudentNumber = "9656748816"
                        },
                        new
                        {
                            Id = "58157f17-b67f-4d19-96fa-d320bd962b37",
                            College = 1,
                            FirstDepartment = 4,
                            Grade = "2BITZ6",
                            Introduction = "531776667589148467810843",
                            Name = "VW61RG",
                            Phone = "71232439153",
                            Qq = "2720710692",
                            State = 10,
                            StudentNumber = "4685781445"
                        },
                        new
                        {
                            Id = "a3048fbe-36e0-41ba-9deb-0b21ad69d34a",
                            College = 2,
                            FirstDepartment = 1,
                            Grade = "OG2WQV",
                            Introduction = "381170447917807875479454",
                            Name = "YADZ2D",
                            Phone = "06168035735",
                            Qq = "9646705289",
                            State = 10,
                            StudentNumber = "2362554266"
                        },
                        new
                        {
                            Id = "932ba6d0-a354-49fe-9b78-f387ef8e9a84",
                            College = 16,
                            FirstDepartment = 5,
                            Grade = "LU26UT",
                            Introduction = "352796682927869809715701",
                            Name = "IM1T1B",
                            Phone = "07562238525",
                            Qq = "3457205873",
                            State = 10,
                            StudentNumber = "1199799255"
                        },
                        new
                        {
                            Id = "21e90bd6-cff6-415d-bae8-581dc7f6649b",
                            College = 5,
                            FirstDepartment = 5,
                            Grade = "DCRQ59",
                            Introduction = "279021288940700885986974",
                            Name = "82BG3G",
                            Phone = "74326021756",
                            Qq = "4588219384",
                            State = 10,
                            StudentNumber = "8573629171"
                        },
                        new
                        {
                            Id = "3f7a64d2-5e1e-40cb-a092-9380bd71d779",
                            College = 25,
                            FirstDepartment = 1,
                            Grade = "K1FYXY",
                            Introduction = "864149562271850645817689",
                            Name = "FNIPCD",
                            Phone = "22206131562",
                            Qq = "9875129846",
                            State = 10,
                            StudentNumber = "6581624064"
                        },
                        new
                        {
                            Id = "b093ed10-4b63-41b3-9995-d0188ecb4f84",
                            College = 6,
                            FirstDepartment = 3,
                            Grade = "YV08FL",
                            Introduction = "874513513751101425909532",
                            Name = "NFLYJ7",
                            Phone = "01562391111",
                            Qq = "8426813256",
                            State = 10,
                            StudentNumber = "1950315869"
                        },
                        new
                        {
                            Id = "b5cca599-288b-4363-9aa3-596cb357c3cc",
                            College = 5,
                            FirstDepartment = 6,
                            Grade = "4A1AF2",
                            Introduction = "189064226923990217287208",
                            Name = "PRW2YS",
                            Phone = "84235173009",
                            Qq = "9962376806",
                            State = 10,
                            StudentNumber = "5317879422"
                        },
                        new
                        {
                            Id = "931a6532-33dc-4ede-8c2a-dc3102713596",
                            College = 7,
                            FirstDepartment = 3,
                            Grade = "D53LI8",
                            Introduction = "286653859379761067165106",
                            Name = "ZKPLYG",
                            Phone = "00801715873",
                            Qq = "3866125812",
                            State = 10,
                            StudentNumber = "8318943698"
                        },
                        new
                        {
                            Id = "f0f33813-20aa-4b97-b05d-50da40dae5f6",
                            College = 25,
                            FirstDepartment = 3,
                            Grade = "WCNVZE",
                            Introduction = "241872633845353164318695",
                            Name = "5DHRPE",
                            Phone = "17632823601",
                            Qq = "1464278862",
                            State = 10,
                            StudentNumber = "0151757704"
                        },
                        new
                        {
                            Id = "5fc793fb-a954-4540-a4de-8e7f20f4963b",
                            College = 25,
                            FirstDepartment = 3,
                            Grade = "GZ9KNG",
                            Introduction = "227251034452646621072933",
                            Name = "65OFKN",
                            Phone = "79225216459",
                            Qq = "0595938432",
                            State = 10,
                            StudentNumber = "5662697861"
                        },
                        new
                        {
                            Id = "7778662e-6fb6-4bd5-9fcd-bd18c0ae03bb",
                            College = 17,
                            FirstDepartment = 3,
                            Grade = "ADXU63",
                            Introduction = "364383890009131659037464",
                            Name = "NFRPSV",
                            Phone = "41996471143",
                            Qq = "6743414737",
                            State = 10,
                            StudentNumber = "6211298827"
                        },
                        new
                        {
                            Id = "a03a0c6d-4103-47bc-b4c2-1f6ac7d55de4",
                            College = 16,
                            FirstDepartment = 2,
                            Grade = "OUZ615",
                            Introduction = "835671848056608561412097",
                            Name = "V6Z97E",
                            Phone = "25203900076",
                            Qq = "6716237788",
                            State = 10,
                            StudentNumber = "8649305789"
                        },
                        new
                        {
                            Id = "ca0b1a84-5da9-426c-9411-81d1705e61d1",
                            College = 25,
                            FirstDepartment = 6,
                            Grade = "W80G0C",
                            Introduction = "854776122954338933708432",
                            Name = "TDR7WR",
                            Phone = "38345039971",
                            Qq = "9715023451",
                            State = 10,
                            StudentNumber = "0905596999"
                        },
                        new
                        {
                            Id = "9ae7b914-51e5-48aa-b1c8-403708342e7d",
                            College = 0,
                            FirstDepartment = 2,
                            Grade = "S0ZE4C",
                            Introduction = "461601356918526977999758",
                            Name = "BUKWIB",
                            Phone = "44502813233",
                            Qq = "7211221989",
                            State = 10,
                            StudentNumber = "2019174424"
                        },
                        new
                        {
                            Id = "688b3fee-bc78-4312-b272-13a19c2c3e2b",
                            College = 26,
                            FirstDepartment = 4,
                            Grade = "JQ2FAA",
                            Introduction = "442646345696874769966819",
                            Name = "0LA36C",
                            Phone = "26918567805",
                            Qq = "0007261449",
                            State = 10,
                            StudentNumber = "5089760906"
                        },
                        new
                        {
                            Id = "8eb6e480-2ff2-430f-bc11-244d843b23eb",
                            College = 10,
                            FirstDepartment = 4,
                            Grade = "QIMQQO",
                            Introduction = "090698025437065839112027",
                            Name = "9N8U1T",
                            Phone = "43556855142",
                            Qq = "4645685749",
                            State = 10,
                            StudentNumber = "8541327277"
                        },
                        new
                        {
                            Id = "867b4441-c9e1-4ea3-825a-0ccd6af1a34b",
                            College = 11,
                            FirstDepartment = 6,
                            Grade = "33GYK3",
                            Introduction = "812484599343174115234520",
                            Name = "Y4ZQL8",
                            Phone = "76974016678",
                            Qq = "7797103487",
                            State = 10,
                            StudentNumber = "8210180885"
                        },
                        new
                        {
                            Id = "b14b0c3c-101e-44f9-845f-d0b94eaf0d1c",
                            College = 8,
                            FirstDepartment = 6,
                            Grade = "I6L16F",
                            Introduction = "245108472253975974443840",
                            Name = "0PUQG1",
                            Phone = "23576696734",
                            Qq = "8335798784",
                            State = 10,
                            StudentNumber = "5115674916"
                        },
                        new
                        {
                            Id = "f2f87d8f-e346-449a-8b91-024b2088f773",
                            College = 23,
                            FirstDepartment = 3,
                            Grade = "D5NJHR",
                            Introduction = "907554369064811286051900",
                            Name = "3W14LN",
                            Phone = "74855700983",
                            Qq = "6037206216",
                            State = 10,
                            StudentNumber = "8142689861"
                        },
                        new
                        {
                            Id = "0bf2e849-4afc-459c-8c07-5f4ead012e09",
                            College = 25,
                            FirstDepartment = 5,
                            Grade = "SOFY0X",
                            Introduction = "249620629924820842593731",
                            Name = "V1SSUX",
                            Phone = "00394876239",
                            Qq = "4048577224",
                            State = 10,
                            StudentNumber = "1090299967"
                        },
                        new
                        {
                            Id = "3f7162f4-1e7d-4d7d-b1e9-dc4d14b97548",
                            College = 6,
                            FirstDepartment = 5,
                            Grade = "17LM6L",
                            Introduction = "346837290208177940820543",
                            Name = "LBNBFH",
                            Phone = "90760931846",
                            Qq = "1462746588",
                            State = 10,
                            StudentNumber = "0390189229"
                        },
                        new
                        {
                            Id = "e45cae0e-c725-43e2-b3b9-d5f8baf79572",
                            College = 17,
                            FirstDepartment = 4,
                            Grade = "SGRXHJ",
                            Introduction = "054207485069021399836293",
                            Name = "RQ3PZX",
                            Phone = "86660875795",
                            Qq = "1298393743",
                            State = 10,
                            StudentNumber = "9223039114"
                        },
                        new
                        {
                            Id = "ffe1c4b0-2cff-4e7e-83d2-e12380a1d42a",
                            College = 4,
                            FirstDepartment = 3,
                            Grade = "FX62EU",
                            Introduction = "905956407621966235044716",
                            Name = "ULJIEG",
                            Phone = "21284823836",
                            Qq = "3699731960",
                            State = 10,
                            StudentNumber = "6423836140"
                        },
                        new
                        {
                            Id = "16bf6019-9129-4271-8e7d-f2f9bcc1c5db",
                            College = 13,
                            FirstDepartment = 4,
                            Grade = "JMZD4X",
                            Introduction = "559533502609126782266277",
                            Name = "RF9UGD",
                            Phone = "16781556558",
                            Qq = "1927046227",
                            State = 10,
                            StudentNumber = "3608171666"
                        },
                        new
                        {
                            Id = "c1d244f5-77dd-49ef-ac78-64c23a771236",
                            College = 20,
                            FirstDepartment = 4,
                            Grade = "D2TBPC",
                            Introduction = "818544288354873362902539",
                            Name = "B28D1X",
                            Phone = "55147153279",
                            Qq = "2107683993",
                            State = 10,
                            StudentNumber = "7581738914"
                        },
                        new
                        {
                            Id = "c3a5aadf-8369-4bec-b2f2-21c3b8ff5ec0",
                            College = 24,
                            FirstDepartment = 4,
                            Grade = "9I5RCM",
                            Introduction = "475659418804439900672271",
                            Name = "D615C5",
                            Phone = "83691235687",
                            Qq = "6109568433",
                            State = 10,
                            StudentNumber = "2634010903"
                        },
                        new
                        {
                            Id = "d8fb3554-e6ac-4876-9414-775bf8fcbe69",
                            College = 3,
                            FirstDepartment = 4,
                            Grade = "7XA6C0",
                            Introduction = "556940591142493309780174",
                            Name = "N2H4EH",
                            Phone = "65497884192",
                            Qq = "6350234657",
                            State = 10,
                            StudentNumber = "7811603488"
                        },
                        new
                        {
                            Id = "59cd7dd6-d719-4fd7-8139-9f34afcb0278",
                            College = 1,
                            FirstDepartment = 2,
                            Grade = "6PMP7K",
                            Introduction = "404064837215086517237331",
                            Name = "7EHKYT",
                            Phone = "42327110578",
                            Qq = "2494409109",
                            State = 10,
                            StudentNumber = "4612322994"
                        },
                        new
                        {
                            Id = "186186e0-172c-46b7-8205-24da08a96198",
                            College = 18,
                            FirstDepartment = 4,
                            Grade = "UAVXKM",
                            Introduction = "454825328076567946425802",
                            Name = "L2YX8Z",
                            Phone = "25154214447",
                            Qq = "3295673387",
                            State = 10,
                            StudentNumber = "1973862384"
                        },
                        new
                        {
                            Id = "b7cc5cf0-d07f-4d1b-b250-212820a4c8ec",
                            College = 3,
                            FirstDepartment = 5,
                            Grade = "1XMM0N",
                            Introduction = "011246315448035414912825",
                            Name = "W8NRBP",
                            Phone = "74103924433",
                            Qq = "4514315136",
                            State = 10,
                            StudentNumber = "5882712103"
                        },
                        new
                        {
                            Id = "61d07c1a-6f8e-42dd-bd31-a7434133f290",
                            College = 23,
                            FirstDepartment = 4,
                            Grade = "LBV3LW",
                            Introduction = "596156893909909355225460",
                            Name = "7FENPP",
                            Phone = "21524836697",
                            Qq = "4051271265",
                            State = 10,
                            StudentNumber = "5020736479"
                        },
                        new
                        {
                            Id = "76296a81-e90a-466f-8726-9d5d9fe28474",
                            College = 7,
                            FirstDepartment = 3,
                            Grade = "JJUS27",
                            Introduction = "732014821586956734698420",
                            Name = "GUZDCI",
                            Phone = "62042546715",
                            Qq = "4222964898",
                            State = 10,
                            StudentNumber = "3101180311"
                        },
                        new
                        {
                            Id = "84b29606-6337-4909-84bd-4d13b1253a57",
                            College = 15,
                            FirstDepartment = 2,
                            Grade = "729WZ4",
                            Introduction = "970645670551855514423417",
                            Name = "8G09UZ",
                            Phone = "50943903033",
                            Qq = "3729257204",
                            State = 10,
                            StudentNumber = "9179687169"
                        },
                        new
                        {
                            Id = "82e65658-6c39-4d97-b086-c208dda3f300",
                            College = 21,
                            FirstDepartment = 3,
                            Grade = "N4JC1V",
                            Introduction = "553594938511679295883027",
                            Name = "6XWINH",
                            Phone = "61357260909",
                            Qq = "7339812920",
                            State = 10,
                            StudentNumber = "7973994990"
                        },
                        new
                        {
                            Id = "dcbba3ad-e144-4cdb-a53e-04f60d8a3b1b",
                            College = 23,
                            FirstDepartment = 4,
                            Grade = "LY7HYK",
                            Introduction = "643591750283296488667246",
                            Name = "PLZU00",
                            Phone = "53467567189",
                            Qq = "9270548361",
                            State = 10,
                            StudentNumber = "9511927039"
                        },
                        new
                        {
                            Id = "7b0e6607-3962-4728-9525-9db9acff4fc7",
                            College = 16,
                            FirstDepartment = 4,
                            Grade = "LZYP3A",
                            Introduction = "945121519397654826851268",
                            Name = "2BXH37",
                            Phone = "76559880280",
                            Qq = "8685273768",
                            State = 10,
                            StudentNumber = "3657315118"
                        },
                        new
                        {
                            Id = "2c27b375-723e-467a-ab39-7e2c4bc86109",
                            College = 16,
                            FirstDepartment = 6,
                            Grade = "VFXWM2",
                            Introduction = "224865837183202953376470",
                            Name = "RZ5VM9",
                            Phone = "75373388790",
                            Qq = "5279751945",
                            State = 10,
                            StudentNumber = "9897244999"
                        },
                        new
                        {
                            Id = "577f283b-3feb-4907-a9e2-9c25956b47eb",
                            College = 20,
                            FirstDepartment = 2,
                            Grade = "DK9QJG",
                            Introduction = "537055696413759129641910",
                            Name = "PLHGQC",
                            Phone = "18814980836",
                            Qq = "2276949021",
                            State = 10,
                            StudentNumber = "9594573950"
                        },
                        new
                        {
                            Id = "0d5f8c4e-5d89-4523-8a73-fb58fcb1b209",
                            College = 12,
                            FirstDepartment = 6,
                            Grade = "EXSHD4",
                            Introduction = "512458561102862459068588",
                            Name = "ZXZJ7W",
                            Phone = "84473316793",
                            Qq = "6139711744",
                            State = 10,
                            StudentNumber = "0002971889"
                        },
                        new
                        {
                            Id = "b439fcd4-4ad2-49e0-abdc-57b2978d5da0",
                            College = 19,
                            FirstDepartment = 5,
                            Grade = "WW1X5Z",
                            Introduction = "915736658266588021451984",
                            Name = "68TPWT",
                            Phone = "80285224953",
                            Qq = "4548351848",
                            State = 10,
                            StudentNumber = "9249891049"
                        },
                        new
                        {
                            Id = "c2bab5a5-1620-40be-ad07-46aa8f3ec3d0",
                            College = 22,
                            FirstDepartment = 2,
                            Grade = "KI7S9T",
                            Introduction = "443811898374342125053440",
                            Name = "KRS031",
                            Phone = "57515019994",
                            Qq = "0015523718",
                            State = 10,
                            StudentNumber = "4741225424"
                        },
                        new
                        {
                            Id = "0344d342-e9c9-4051-8c71-6ab3381a3cbf",
                            College = 16,
                            FirstDepartment = 5,
                            Grade = "G2UCMQ",
                            Introduction = "689220013100745496078529",
                            Name = "W2OQGH",
                            Phone = "90812519369",
                            Qq = "7657942547",
                            State = 10,
                            StudentNumber = "0713111768"
                        },
                        new
                        {
                            Id = "7c488bb4-8cf5-48bd-828f-cbd7b1c9ee1f",
                            College = 13,
                            FirstDepartment = 6,
                            Grade = "TT8B4Q",
                            Introduction = "550152203309089636786135",
                            Name = "2N48WD",
                            Phone = "74640089315",
                            Qq = "3967457725",
                            State = 10,
                            StudentNumber = "6839990974"
                        },
                        new
                        {
                            Id = "c4e686f3-caf2-4caf-8f62-8561a4fb86f4",
                            College = 5,
                            FirstDepartment = 4,
                            Grade = "6U46Y2",
                            Introduction = "633704950212750895913660",
                            Name = "YV2BDC",
                            Phone = "09621056590",
                            Qq = "8011236987",
                            State = 10,
                            StudentNumber = "2996233541"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("interviewer.Data.InterviewerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("interviewer.Data.InterviewerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("interviewer.Data.InterviewerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("interviewer.Data.InterviewerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
