// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using interviewer.Data;

#nullable disable

namespace interviewer.Migrations
{
    [DbContext(typeof(InterviewerDbContext))]
    [Migration("20230831042952_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityRole");

                    b.HasData(
                        new
                        {
                            Id = "a4933b64-49b2-4662-b1b6-a3caa9ecb584",
                            ConcurrencyStamp = "7a966263-4a43-4250-9bc5-fd9479746a36",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "bb68e4b7-bc10-4ad1-9bbc-cfda72072b17",
                            ConcurrencyStamp = "f8923ec5-1bad-4b3d-9bdd-fe445d735e66",
                            Name = "Interviewer",
                            NormalizedName = "INTERVIEWER"
                        },
                        new
                        {
                            Id = "317cd16b-8026-4c93-9813-f5082aebd866",
                            ConcurrencyStamp = "c3348a9d-c627-4fb3-9055-ce39a6939e15",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("interviewer.Data.Interviewer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interviewers");
                });

            modelBuilder.Entity("interviewer.Data.InterviewerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InterviewerAccounts");
                });

            modelBuilder.Entity("interviewer.Data.InterviewerUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("interviewer.Data.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("College")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FirstDepartment")
                        .HasColumnType("int");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SecondDepartment")
                        .HasColumnType("int");

                    b.Property<string>("Skills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeChat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("782e2a40-c43e-4321-bb19-99de1d8f0dc3"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("75cc7b94-f1b3-4bf2-8e3d-2db28fd330d9"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("19f1a0b2-70a7-46ad-8170-2efe9c7cf412"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("0d75bd2e-9195-4350-a28b-fb787bf8147e"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("8d14e2f6-9437-4bea-9389-18d8fe8fd0d9"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("f9d5d15e-985c-41fd-9315-150baa5998b1"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("b9adb1dc-809f-4e6a-8826-39d3fe8a5b02"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("dff4752e-b471-4b01-98e2-844727bf3b47"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("ef87c959-ee98-4fa3-926a-8253ffd256f0"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("e42d57b4-691b-4668-88ed-d08b983c3b06"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("1f99c229-2792-4d1d-bc64-543a880e358b"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("c8b1283b-1c8c-431e-aca6-60d137b3db6e"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("1d5d8da9-224f-426a-9b40-38f5f8ad5107"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("c1c902b6-1ad5-4132-af43-b7050b055cb9"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("8f102b11-2e59-4042-8143-ee9908d705da"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("045abdd6-ff8d-487c-a624-8536a3f06a8b"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("6dff981f-4933-48fd-8cc4-93a960d1f907"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("3562b333-fe88-4bf9-b7d1-182f24ef8896"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("d68d5307-5a3b-4f16-8030-7c0b010d1d38"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("a4f77ab8-4136-42f0-9aa2-5d80ffeab4cf"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("e6ee281f-6d8e-45bc-aa03-c08ccae63c02"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("443752c5-3d3a-4a0e-aab7-9084e6c9a1ea"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("f063240f-e57f-4d17-bb2e-0fced9975863"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("30ee1afd-9533-4070-be03-7b07cf80b25e"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("4b37d3b0-64da-46da-bfc4-9ae7733fda43"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("bfad5c41-72a6-4fd2-821a-6abf827feb94"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("f985147d-5c20-4a0d-b28a-dd23bc479834"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("1b638c6a-9438-4a09-a0fb-95964964f055"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("7f4bcb1c-9b88-4fe5-9d24-f12f0a9f5a07"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("84271435-ebb3-4bc3-98c6-35c3f9091e00"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("fab1401a-cca2-4ebc-9d21-3fb744a6e73f"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("35feec4d-ccbb-4fd6-a29f-565152acf5aa"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("7f2dd864-3634-47e3-8f54-e398c1456b51"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("75af736a-b0da-4dbe-bfc8-1b01512f182b"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("feab0340-d2bd-4eff-96f6-08bbafd4342a"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("e1612391-1c2c-41fd-afe3-11a67fe283df"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("243a43a9-c3eb-4ffb-8461-5a02562825e4"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("776a95ec-1a30-4dcb-96d0-4fb34477e3ef"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("631b5757-64eb-47aa-b581-ea3a87b43fe6"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("3dddd41f-f568-4c37-8805-68be01cc333c"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("e7081d69-ad53-4652-97e8-8ad2ba31f35c"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("d39de320-b5d7-4f18-bcda-b4a3c3273adb"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("a695b11c-1f35-4fcb-b60f-6ffd04601380"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("d9d1c963-4272-4622-b643-8017a0bae8ed"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("9b68f913-a437-47c2-b866-005f3d9d109b"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("7aded075-b86c-438b-a34c-4e40395e3003"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("e7e05273-8edf-4120-af9b-b551c9b1365b"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("79da8e7b-6632-4929-a742-49a6b94fbb39"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("d65937f5-cd1b-426a-ac17-d9d22bbcfca1"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("3b7a44ec-afae-49c1-af74-dcd2005cb1b6"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("87ec8397-705e-445e-b775-a6134ed26741"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("b64902ac-6757-4bc3-b226-68dbc4e56adc"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("94922748-7d28-487f-8566-d375637b2d44"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("01fc0e8e-df88-4ad2-bc2e-2b96b6b74f08"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("03319559-a12a-4e32-abe3-94c21dbf1d5b"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("47b84575-981e-472d-8a2b-a4166e6f0b82"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("16e15e93-7aa3-4588-9917-a1a3142974ab"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("b46fa810-7eaa-4652-b570-31d8a0b714a6"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("c778096d-8edb-47ba-9e17-dd5dc988da15"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("888b5f0a-fcab-4b2d-9b1e-32cb894f3f3a"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("4cb6162b-3f93-4ce0-828c-c4b2834c58b5"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("973e6431-f252-4209-b925-7b9150adeba9"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("f0199003-47bb-41ad-9524-1da7261a4800"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("e40ba8af-3e45-4295-926f-becc09d552fb"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("f2f38962-280e-4ea9-91c4-19ea5feb7ea8"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("60ebc69f-cab4-4d21-8a3a-77560694c7d4"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("32cf7b1f-3b8b-420e-86e0-8e7248e639fb"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("0458f26a-f5b1-43f7-a3f1-45e8c6b7d99f"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("6dbaeeeb-a61a-402c-8531-1f4e7d592a24"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("76239523-3c5c-4460-b4c9-42d5b512b7af"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("4994e296-7207-4e6d-a60e-3edd095244f8"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("a748692f-792a-4521-b322-7ee2e6cf110c"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("9c9f75c6-3fda-4497-861e-1eefd50a9648"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("8efa5fcb-c24c-4dc6-8afe-665316ada551"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("17122ee4-fd5a-4aaa-94cb-461b6686dc2c"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("874999ac-902f-481a-8fa0-49fe1eab5303"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("38fb90cf-164b-44f2-80ac-a888f672483b"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("db217512-7ed0-4601-ac1c-540f0a602ec2"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("1f7fb796-5828-430c-b7ff-35dcf2a976ff"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("f363d929-7bb6-4979-b2b5-2ee2fdbcbd8d"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("7a11dcf1-b2ae-4fe2-8454-6816cd262880"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("d04f585b-b052-46e3-a208-8e37cb438421"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("cf14c201-14b6-4df4-ad07-74c1e2c4a710"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("bac35c0e-d6df-4641-bbae-870427770117"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("227f6d27-a569-43f1-b070-7506e7d71b28"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("8c2fcc2f-38b9-40d2-8447-7aac0f254fe6"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("a914370a-fcc6-41c7-ad0a-2c6b3a88d0b3"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("ad9c32bd-3639-4e64-8a38-37fe8a26675a"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("8f28b820-d1a5-4ea1-a34e-88b121f9bdfa"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("606ff42f-ada3-4c30-b068-84121e0c5683"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("995f9323-5f15-4343-8a7c-33321b03070d"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("b2388e9f-f805-467d-99aa-143d710bdb68"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("c679380d-bd3e-4647-9acc-c6279c74518c"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("7f53ca1c-1ed1-4959-839e-c2a6c2ae9946"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("d574d671-b3b7-4487-a657-cecca1331046"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("369ef227-c917-4449-8c0f-464f2f004fb3"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("1ed322a0-7f04-4cf2-97b7-f14377ebd0d4"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("a982bcdc-e158-400a-866c-c03a936193e0"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("886d9226-ee57-4288-a35a-e880119ab167"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("5916c495-6f87-4aff-9242-b2a8f8f14d7a"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        });
                });

            modelBuilder.Entity("interviewer.Data.StudentAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StudentAccounts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("interviewer.Data.InterviewerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("interviewer.Data.InterviewerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("interviewer.Data.InterviewerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("interviewer.Data.InterviewerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
