// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using interviewer.Data;

#nullable disable

namespace interviewer.Migrations
{
    [DbContext(typeof(InterviewerDbContext))]
    partial class InterviewerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ce0156f1-1293-4e99-b1f3-4f3cc84713da"),
                            ConcurrencyStamp = "4c385851-d18f-4626-91f4-5b8244d0e47c",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("1ff75dee-9346-43fa-a975-1f561a7deab2"),
                            ConcurrencyStamp = "12e74a3c-9833-44b9-aa94-770325aae6f7",
                            Name = "Interviewer",
                            NormalizedName = "INTERVIEWER"
                        },
                        new
                        {
                            Id = new Guid("b63f7c2d-4172-4016-8a1a-f594f621e9c1"),
                            ConcurrencyStamp = "25c7af36-d867-4b5b-b0e2-477a45d30b34",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("interviewer.Data.Interviewer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interviewers");
                });

            modelBuilder.Entity("interviewer.Data.InterviewerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InterviewerAccounts");
                });

            modelBuilder.Entity("interviewer.Data.InterviewerUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("interviewer.Data.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("College")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FirstDepartment")
                        .HasColumnType("int");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SecondDepartment")
                        .HasColumnType("int");

                    b.Property<string>("Skills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeChat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("edaeddc0-f7bd-4456-913d-deba5b33c456"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("cecdb11e-9512-48d3-b05b-36d2b71e31e2"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("0b064738-e640-4836-b533-4bf5977f7d26"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("6fcd63de-e9b0-40f1-bc72-a07a2eb7c353"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("3fd1bd24-adda-41b8-a149-920e3790ba6d"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("12b0f689-a47a-40f1-818a-a63f1e22ce66"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("0bce99b9-ebcd-4c88-8b09-e75e7ff02084"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("12ccbe4f-eecc-41b5-875a-e728ead133e1"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("6e20aac2-24b4-4018-9033-d886c85ad33f"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("6990c9e4-43b6-48d0-83f3-027b9e069f15"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("40e911ea-1815-4df7-b6d3-f666f0a9604a"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("55f5987b-fb5a-4674-b077-a1d82c37eda4"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("e6c78b16-17cf-4d98-a97c-adabf9de7eb7"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("3c060deb-1278-418b-854e-8e602371d35d"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("fc9d5405-f9f7-47e3-9a8e-19f4c812da25"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("21ff3d77-627e-418f-90d8-f118cc4cd80d"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("6d28e9c6-47b6-4d54-b90b-482f99bce79c"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("cdeab141-92d0-4d49-924f-a6259e1cc4e4"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("e9738cde-9ef8-4d9f-a964-4024be2b7bee"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("aa4f0d31-6a76-4b3d-b3ac-1ca66ee84ce5"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("8613f4ff-c997-45f0-a39c-03d461f0b84d"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("853ff7b7-cfe8-4d41-80e9-39f23f71f247"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("ce90517b-b198-49b9-8262-740366f5cda0"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("454eb92d-9a6a-4de2-832c-c8cb859d902b"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("92778e71-9698-491f-8a7c-715fda753b68"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("838a19ec-f872-4f49-8ba0-e719dfc66898"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("193c011e-39c7-4113-9077-8d73d7761a31"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("58bc228a-bc04-432c-b1a8-b0532d20c22b"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("3922fe2f-1949-4431-ba7a-55d778e94b83"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("cc60d8f1-ed4b-42de-ae1b-d9d8b860cd19"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("7e4ebea1-ec9c-4388-baa2-9439b457db95"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("f7a86267-ccc3-467b-9c58-55f6d4fc472b"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("ec5a826f-d899-4e94-aa67-8dc3a28be275"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("ca76dc0e-432e-42b1-b676-d2208464aed3"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("86c28181-79e0-47ec-9d38-481eef0c05d1"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("d6828423-4610-4ebe-908c-e76f4c6adf46"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("1beeae0e-cf89-4c65-bd3f-a06232d66954"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("14417579-7fba-4052-9fa1-1910b3d62a56"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("fbb26032-a4b0-48ad-8858-41efe0c87279"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("24a2b3db-00ee-4296-9f3c-384c9b01ca59"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("28a7995e-db42-47b9-a648-de8ae33c051a"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("6f28e6ae-fd40-4985-92b8-bdfd521845d6"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("7b59cd00-7021-428c-b99e-d08af8ec6409"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("1f18f0f2-7a8b-44af-9ff9-2485d320ee12"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("40615c66-76b1-45a7-9970-b85841ae9d24"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("907237ec-2291-4644-9870-4aed96f6fe16"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("d353ea4d-211e-4113-bd2c-be33dadf25ed"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("e5b70da9-5713-4858-84ef-ec233b21ade1"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("051bb7b7-c3d0-49ba-8c5b-2a06b1f5f2d8"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("5d3d03b5-06bd-49e6-ac16-8f9671ee238c"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("8d200d64-bea7-444a-92b7-f00e7a9e78ac"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("371c2eb0-52b8-4979-ab7f-d92e131b09ed"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("b84b7b18-41a2-4013-9773-6cf32f5a1244"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("dc814079-4ad6-490c-bb49-3ca539a23eeb"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("e9f52f7f-03de-4689-954d-3c20485e594c"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("852757eb-233f-4820-ace0-a5d206fc61fd"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("c84a7e71-8fa7-443d-a81a-dbd5d113ef81"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("3c58f026-cf60-4c14-9596-f6c00c3b1503"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("f54c4812-1c3f-4538-8ec0-8bfd65a01e12"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("9d7c1f76-601f-4fa5-ae87-099be7db13a4"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("b75d8743-8f80-4789-900c-2621f01aeab7"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("6343d11f-89c5-4da0-b6f2-b9bc36d49b95"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("3f92efa2-6b4e-4c4d-a0cb-1204adf6cdad"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("54a9decf-a0d5-4d94-916a-c385e725ff20"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("b373615d-dceb-4e37-9229-33d52a17bcc5"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("be1658ed-3370-4e23-bc0d-20db98d45b99"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("a8e4d2fa-f33b-4f55-9d69-4c3854fa827d"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("c048fcc7-7056-444f-ab91-9198c621be98"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("5c521ce3-19bd-4ca0-a022-908d5756690f"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("c3517b6c-0aa1-4a6e-81e8-316b182038f0"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("b8cce48e-90e2-4518-861f-6953f6d82680"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("d60b1ec5-778e-4064-a36f-0e31dbec1ea4"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("9bffe19d-6d51-46a1-8d17-853499df6e3e"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("b1ed936b-d896-4f44-87c2-f36f460a0066"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("b67e3cfd-c739-44a3-85d2-2bb9ea0503ef"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("0a71e2a0-d6fd-499f-9c4f-689a504f4762"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("a1643251-93c4-4ec7-b230-15ad00017d79"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("89f2e417-5724-45c2-a4c5-248556bdc134"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("6b15c18f-f2b8-4b5c-b0aa-08543ce40fa4"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("917eb1d2-6135-4869-bdc0-95b0ca5d439c"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("cdf13dc1-573d-42a5-8483-8a13f502108c"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("d994adbd-e346-4746-a5b0-a00a213931e1"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("5100f01a-7fb8-4b3d-b1bb-97022c2079fa"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("f9720e32-fe1e-4db1-9b29-c2038a938b29"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("a623774d-afc1-462f-8719-ff127ff8b0e2"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("dd3f407b-de6d-40e3-9517-5f3c1775b9a6"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("3dfeaeec-5b9b-4a75-b8ba-60309d6b8c28"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("40032199-4acc-42a6-819c-c62e1c34b40e"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("c9bf18fd-2ed0-4618-96e8-ed4d2c3ac617"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("33af5166-fb5b-43e4-a7e2-80e4b5679077"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("dd909617-f98b-47b2-8783-b0ab690dba7b"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("94590279-538a-4a8b-adbe-062cc22586f2"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("d2e4825e-cc5c-4a16-8eee-2ef200cbf693"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("716b6af4-d6e1-41ba-a7d1-12c836b385d0"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("aa0863e0-2e24-4879-9902-b9d899183037"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("128fba97-5b17-45a1-9f6e-5390cc991b27"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("b6a06f8e-e707-47a3-845c-507443cbf0ee"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("1aa337dc-03fe-4df0-83ad-816aab6b9915"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("86d1e4fe-182c-4d8d-b2cd-c095fc6edc38"),
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = new Guid("3193d1e8-c02b-4fe2-8342-30ef18d74940"),
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        });
                });

            modelBuilder.Entity("interviewer.Data.StudentAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StudentAccounts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("interviewer.Data.InterviewerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("interviewer.Data.InterviewerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("interviewer.Data.InterviewerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("interviewer.Data.InterviewerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
